//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.BaseResource", typeof(BaseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access or Terrain Situation.
        /// </summary>
        public static string AccessOrTerrainSituation {
            get {
                return ResourceManager.GetString("AccessOrTerrainSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Notes.
        /// </summary>
        public static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconstruction?.
        /// </summary>
        public static string AllowsDeconstruction {
            get {
                return ResourceManager.GetString("AllowsDeconstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Complexity.
        /// </summary>
        public static string BaseComplexity {
            get {
                return ResourceManager.GetString("BaseComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Type.
        /// </summary>
        public static string BaseType {
            get {
                return ResourceManager.GetString("BaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builderlink on Wiki.
        /// </summary>
        public static string BuilderLinkOnWiki {
            get {
                return ResourceManager.GetString("BuilderLinkOnWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilized.
        /// </summary>
        public static string CivilizedBy {
            get {
                return ResourceManager.GetString("CivilizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Finished.
        /// </summary>
        public static string DateFinished {
            get {
                return ResourceManager.GetString("DateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Survey.
        /// </summary>
        public static string DateOfSurvey {
            get {
                return ResourceManager.GetString("DateOfSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Started.
        /// </summary>
        public static string DateStarted {
            get {
                return ResourceManager.GetString("DateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Sequence.
        /// </summary>
        public static string DocSequence {
            get {
                return ResourceManager.GetString("DocSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Link 1.
        /// </summary>
        public static string ExternalLink1 {
            get {
                return ResourceManager.GetString("ExternalLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Link 2.
        /// </summary>
        public static string ExternalLink2 {
            get {
                return ResourceManager.GetString("ExternalLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Extractor?.
        /// </summary>
        public static string GasExtractor {
            get {
                return ResourceManager.GetString("GasExtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Store Capacity.
        /// </summary>
        public static string GasStoreCapacity {
            get {
                return ResourceManager.GetString("GasStoreCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena.
        /// </summary>
        public static string HasArena {
            get {
                return ResourceManager.GetString("HasArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        public static string HasFarm {
            get {
                return ResourceManager.GetString("HasFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geobay.
        /// </summary>
        public static string HasGeobay {
            get {
                return ResourceManager.GetString("HasGeobay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing Pad?.
        /// </summary>
        public static string HasLandingPad {
            get {
                return ResourceManager.GetString("HasLandingPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racetrack?.
        /// </summary>
        public static string HasRacetrack {
            get {
                return ResourceManager.GetString("HasRacetrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Terminal?.
        /// </summary>
        public static string HasTradeTerminal {
            get {
                return ResourceManager.GetString("HasTradeTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Description.
        /// </summary>
        public static string LayoutDescription {
            get {
                return ResourceManager.GetString("LayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Extractor?.
        /// </summary>
        public static string MiningExtractor {
            get {
                return ResourceManager.GetString("MiningExtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Store Capacity.
        /// </summary>
        public static string MiningStoreCapacity {
            get {
                return ResourceManager.GetString("MiningStoreCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby POI.
        /// </summary>
        public static string NearByPOIs {
            get {
                return ResourceManager.GetString("NearByPOIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Notes.
        /// </summary>
        public static string PersonalNotes {
            get {
                return ResourceManager.GetString("PersonalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Repository Link.
        /// </summary>
        public static string PortalRepositoryLink {
            get {
                return ResourceManager.GetString("PortalRepositoryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Situation.
        /// </summary>
        public static string PowerSituation {
            get {
                return ResourceManager.GetString("PowerSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release version.
        /// </summary>
        public static string ReleaseVersion {
            get {
                return ResourceManager.GetString("ReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Text.
        /// </summary>
        public static string SummaryText {
            get {
                return ResourceManager.GetString("SummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor ID.
        /// </summary>
        public static string Surveyor {
            get {
                return ResourceManager.GetString("Surveyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Base.
        /// </summary>
        public static string TypeOfBase {
            get {
                return ResourceManager.GetString("TypeOfBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videoes.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Link.
        /// </summary>
        public static string WikiLink {
            get {
                return ResourceManager.GetString("WikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XX (second coord).
        /// </summary>
        public static string XXSecondCoordinate {
            get {
                return ResourceManager.GetString("XXSecondCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YY (first coord).
        /// </summary>
        public static string YYFirstCoordinate {
            get {
                return ResourceManager.GetString("YYFirstCoordinate", resourceCulture);
            }
        }
    }
}
