//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BiomeDescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BiomeDescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.BiomeDescriptionResource", typeof(BiomeDescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned (Barren).
        /// </summary>
        public static string BarrenAbandoned {
            get {
                return ResourceManager.GetString("BarrenAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barren (Barren).
        /// </summary>
        public static string BarrenBarren {
            get {
                return ResourceManager.GetString("BarrenBarren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleak (Barren).
        /// </summary>
        public static string BarrenBleak {
            get {
                return ResourceManager.GetString("BarrenBleak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert (Barren).
        /// </summary>
        public static string BarrenDesert {
            get {
                return ResourceManager.GetString("BarrenDesert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desolate (Barren).
        /// </summary>
        public static string BarrenDesolate {
            get {
                return ResourceManager.GetString("BarrenDesolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusty (Barren).
        /// </summary>
        public static string BarrenDusty {
            get {
                return ResourceManager.GetString("BarrenDusty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infected Dustbowl (Barren).
        /// </summary>
        public static string BarrenInfectedDustbowl {
            get {
                return ResourceManager.GetString("BarrenInfectedDustbowl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infested (Barren).
        /// </summary>
        public static string BarrenInfested {
            get {
                return ResourceManager.GetString("BarrenInfested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parched (Barren).
        /// </summary>
        public static string BarrenParched {
            get {
                return ResourceManager.GetString("BarrenParched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocky (Barren).
        /// </summary>
        public static string BarrenRocky {
            get {
                return ResourceManager.GetString("BarrenRocky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruined Dustbowl (Barren).
        /// </summary>
        public static string BarrenRuinedDustbowl {
            get {
                return ResourceManager.GetString("BarrenRuinedDustbowl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tainted (Barren).
        /// </summary>
        public static string BarrenTainted {
            get {
                return ResourceManager.GetString("BarrenTainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorsphere (Barren).
        /// </summary>
        public static string BarrenTerrorsphere {
            get {
                return ResourceManager.GetString("BarrenTerrorsphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind-swept (Barren).
        /// </summary>
        public static string BarrenWindswept {
            get {
                return ResourceManager.GetString("BarrenWindswept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned (Dead).
        /// </summary>
        public static string DeadAbandoned {
            get {
                return ResourceManager.GetString("DeadAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airless (Dead).
        /// </summary>
        public static string DeadAirless {
            get {
                return ResourceManager.GetString("DeadAirless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead (Dead).
        /// </summary>
        public static string DeadDead {
            get {
                return ResourceManager.GetString("DeadDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desolate (Dead).
        /// </summary>
        public static string DeadDesolate {
            get {
                return ResourceManager.GetString("DeadDesolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty (Dead).
        /// </summary>
        public static string DeadEmpty {
            get {
                return ResourceManager.GetString("DeadEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forsaken (Dead).
        /// </summary>
        public static string DeadForsaken {
            get {
                return ResourceManager.GetString("DeadForsaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life-Incompatible (Dead).
        /// </summary>
        public static string DeadLifeIncompatible {
            get {
                return ResourceManager.GetString("DeadLifeIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifeless (Dead).
        /// </summary>
        public static string DeadLifeless {
            get {
                return ResourceManager.GetString("DeadLifeless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Atmosphere (Dead).
        /// </summary>
        public static string DeadLowAtmosphere {
            get {
                return ResourceManager.GetString("DeadLowAtmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terraforming Catastrophe (Dead).
        /// </summary>
        public static string DeadTerraformingCatastrophe {
            get {
                return ResourceManager.GetString("DeadTerraformingCatastrophe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bladed (Exotic).
        /// </summary>
        public static string ExoticBladed {
            get {
                return ResourceManager.GetString("ExoticBladed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breached (Exotic).
        /// </summary>
        public static string ExoticBreached {
            get {
                return ResourceManager.GetString("ExoticBreached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubbling (Exotic).
        /// </summary>
        public static string ExoticBubbling {
            get {
                return ResourceManager.GetString("ExoticBubbling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabled (Exotic).
        /// </summary>
        public static string ExoticCabled {
            get {
                return ResourceManager.GetString("ExoticCabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcified (Exotic).
        /// </summary>
        public static string ExoticCalcified {
            get {
                return ResourceManager.GetString("ExoticCalcified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capped (Exotic).
        /// </summary>
        public static string ExoticCapped {
            get {
                return ResourceManager.GetString("ExoticCapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clouds of Haunted Green (Exotic).
        /// </summary>
        public static string ExoticCloudsofHauntedGreen {
            get {
                return ResourceManager.GetString("ExoticCloudsofHauntedGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columned (Exotic).
        /// </summary>
        public static string ExoticColumned {
            get {
                return ResourceManager.GetString("ExoticColumned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoured (Exotic).
        /// </summary>
        public static string ExoticContoured {
            get {
                return ResourceManager.GetString("ExoticContoured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted (Exotic).
        /// </summary>
        public static string ExoticCorrupted {
            get {
                return ResourceManager.GetString("ExoticCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson (Exotic).
        /// </summary>
        public static string ExoticCrimson {
            get {
                return ResourceManager.GetString("ExoticCrimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doomed (Exotic).
        /// </summary>
        public static string ExoticDoomed {
            get {
                return ResourceManager.GetString("ExoticDoomed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erased (Exotic).
        /// </summary>
        public static string ExoticErased {
            get {
                return ResourceManager.GetString("ExoticErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finned (Exotic).
        /// </summary>
        public static string ExoticFinned {
            get {
                return ResourceManager.GetString("ExoticFinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fissured (Exotic).
        /// </summary>
        public static string ExoticFissured {
            get {
                return ResourceManager.GetString("ExoticFissured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foaming (Exotic).
        /// </summary>
        public static string ExoticFoaming {
            get {
                return ResourceManager.GetString("ExoticFoaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractured (Exotic).
        /// </summary>
        public static string ExoticFractured {
            get {
                return ResourceManager.GetString("ExoticFractured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmented (Exotic).
        /// </summary>
        public static string ExoticFragmented {
            get {
                return ResourceManager.GetString("ExoticFragmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frothing (Exotic).
        /// </summary>
        public static string ExoticFrothing {
            get {
                return ResourceManager.GetString("ExoticFrothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fungal (Exotic).
        /// </summary>
        public static string ExoticFungal {
            get {
                return ResourceManager.GetString("ExoticFungal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glassy (Exotic).
        /// </summary>
        public static string ExoticGlassy {
            get {
                return ResourceManager.GetString("ExoticGlassy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexagonal (Exotic).
        /// </summary>
        public static string ExoticHexagonal {
            get {
                return ResourceManager.GetString("ExoticHexagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infected (Exotic).
        /// </summary>
        public static string ExoticInfected {
            get {
                return ResourceManager.GetString("ExoticInfected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malfunctioning (Exotic).
        /// </summary>
        public static string ExoticMalfunctioning {
            get {
                return ResourceManager.GetString("ExoticMalfunctioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical (Exotic).
        /// </summary>
        public static string ExoticMechanical {
            get {
                return ResourceManager.GetString("ExoticMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic (Exotic).
        /// </summary>
        public static string ExoticMetallic {
            get {
                return ResourceManager.GetString("ExoticMetallic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallurgic (Exotic).
        /// </summary>
        public static string ExoticMetallurgic {
            get {
                return ResourceManager.GetString("ExoticMetallurgic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon of Light (Exotic).
        /// </summary>
        public static string ExoticMoonofLight {
            get {
                return ResourceManager.GetString("ExoticMoonofLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ossified (Exotic).
        /// </summary>
        public static string ExoticOssified {
            get {
                return ResourceManager.GetString("ExoticOssified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrified (Exotic).
        /// </summary>
        public static string ExoticPetrified {
            get {
                return ResourceManager.GetString("ExoticPetrified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillared (Exotic).
        /// </summary>
        public static string ExoticPillared {
            get {
                return ResourceManager.GetString("ExoticPillared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planetary Anomaly (Exotic).
        /// </summary>
        public static string ExoticPlanetaryAnomaly {
            get {
                return ResourceManager.GetString("ExoticPlanetaryAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet of Light (Exotic).
        /// </summary>
        public static string ExoticPlanetofLight {
            get {
                return ResourceManager.GetString("ExoticPlanetofLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plated (Exotic).
        /// </summary>
        public static string ExoticPlated {
            get {
                return ResourceManager.GetString("ExoticPlated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rattling (Exotic).
        /// </summary>
        public static string ExoticRattling {
            get {
                return ResourceManager.GetString("ExoticRattling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [REDACTED] (Exotic).
        /// </summary>
        public static string ExoticRedacted {
            get {
                return ResourceManager.GetString("ExoticRedacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaly (Exotic).
        /// </summary>
        public static string ExoticScaly {
            get {
                return ResourceManager.GetString("ExoticScaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharded (Exotic).
        /// </summary>
        public static string ExoticSharded {
            get {
                return ResourceManager.GetString("ExoticSharded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shattered (Exotic).
        /// </summary>
        public static string ExoticShattered {
            get {
                return ResourceManager.GetString("ExoticShattered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell-Strewn (Exotic).
        /// </summary>
        public static string ExoticShellStrewn {
            get {
                return ResourceManager.GetString("ExoticShellStrewn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeletal (Exotic).
        /// </summary>
        public static string ExoticSkeletal {
            get {
                return ResourceManager.GetString("ExoticSkeletal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spined (Exotic).
        /// </summary>
        public static string ExoticSpined {
            get {
                return ResourceManager.GetString("ExoticSpined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporal (Exotic).
        /// </summary>
        public static string ExoticSporal {
            get {
                return ResourceManager.GetString("ExoticSporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary (Exotic).
        /// </summary>
        public static string ExoticTemporary {
            get {
                return ResourceManager.GetString("ExoticTemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirsty (Exotic).
        /// </summary>
        public static string ExoticThirsty {
            get {
                return ResourceManager.GetString("ExoticThirsty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webbed (Exotic).
        /// </summary>
        public static string ExoticWebbed {
            get {
                return ResourceManager.GetString("ExoticWebbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctic (Frozen).
        /// </summary>
        public static string FrozenArctic {
            get {
                return ResourceManager.GetString("FrozenArctic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing (Frozen).
        /// </summary>
        public static string FrozenFreezing {
            get {
                return ResourceManager.GetString("FrozenFreezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frostbound (Frozen).
        /// </summary>
        public static string FrozenFrostbound {
            get {
                return ResourceManager.GetString("FrozenFrostbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen (Frozen).
        /// </summary>
        public static string FrozenFrozen {
            get {
                return ResourceManager.GetString("FrozenFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen Hell (Frozen).
        /// </summary>
        public static string FrozenFrozenHell {
            get {
                return ResourceManager.GetString("FrozenFrozenHell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glacial (Frozen).
        /// </summary>
        public static string FrozenGlacial {
            get {
                return ResourceManager.GetString("FrozenGlacial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiemal (Frozen).
        /// </summary>
        public static string FrozenHiemal {
            get {
                return ResourceManager.GetString("FrozenHiemal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperborean (Frozen).
        /// </summary>
        public static string FrozenHyperborean {
            get {
                return ResourceManager.GetString("FrozenHyperborean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icebound (Frozen).
        /// </summary>
        public static string FrozenIcebound {
            get {
                return ResourceManager.GetString("FrozenIcebound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icy (Frozen).
        /// </summary>
        public static string FrozenIcy {
            get {
                return ResourceManager.GetString("FrozenIcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icy Abhorrence (Frozen).
        /// </summary>
        public static string FrozenIcyAbhorrence {
            get {
                return ResourceManager.GetString("FrozenIcyAbhorrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infested (Frozen).
        /// </summary>
        public static string FrozenInfested {
            get {
                return ResourceManager.GetString("FrozenInfested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-zero (Frozen).
        /// </summary>
        public static string FrozenSubZero {
            get {
                return ResourceManager.GetString("FrozenSubZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory β - Titan (Gas Giant).
        /// </summary>
        public static string GasGiantMemoryTitan {
            get {
                return ResourceManager.GetString("GasGiantMemoryTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrified Giant (Gas Giant).
        /// </summary>
        public static string GasGiantPetrifiedGiant {
            get {
                return ResourceManager.GetString("GasGiantPetrifiedGiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD3 (Gas Giant).
        /// </summary>
        public static string GasGiantTBD3 {
            get {
                return ResourceManager.GetString("GasGiantTBD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD4 (Gas Giant).
        /// </summary>
        public static string GasGiantTBD4 {
            get {
                return ResourceManager.GetString("GasGiantTBD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contaminated (Irradiated).
        /// </summary>
        public static string IrradiatedContaminated {
            get {
                return ResourceManager.GetString("IrradiatedContaminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decaying Nuclear (Irradiated).
        /// </summary>
        public static string IrradiatedDecayingNuclear {
            get {
                return ResourceManager.GetString("IrradiatedDecayingNuclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma-Intensive (Irradiated).
        /// </summary>
        public static string IrradiatedGammaIntensive {
            get {
                return ResourceManager.GetString("IrradiatedGammaIntensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Energy (Irradiated).
        /// </summary>
        public static string IrradiatedHighEnergy {
            get {
                return ResourceManager.GetString("IrradiatedHighEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Radio Source (Irradiated).
        /// </summary>
        public static string IrradiatedHighRadioSource {
            get {
                return ResourceManager.GetString("IrradiatedHighRadioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infested (Irradiated).
        /// </summary>
        public static string IrradiatedInfested {
            get {
                return ResourceManager.GetString("IrradiatedInfested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irradiated (Irradiated).
        /// </summary>
        public static string IrradiatedIrradiated {
            get {
                return ResourceManager.GetString("IrradiatedIrradiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isotopic (Irradiated).
        /// </summary>
        public static string IrradiatedIsotopic {
            get {
                return ResourceManager.GetString("IrradiatedIsotopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutated (Irradiated).
        /// </summary>
        public static string IrradiatedMutated {
            get {
                return ResourceManager.GetString("IrradiatedMutated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclear (Irradiated).
        /// </summary>
        public static string IrradiatedNuclear {
            get {
                return ResourceManager.GetString("IrradiatedNuclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radioactive (Irradiated).
        /// </summary>
        public static string IrradiatedRadioactive {
            get {
                return ResourceManager.GetString("IrradiatedRadioactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radioactive Abomination (Irradiated).
        /// </summary>
        public static string IrradiatedRadioactiveAbomination {
            get {
                return ResourceManager.GetString("IrradiatedRadioactiveAbomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supercritical (Irradiated).
        /// </summary>
        public static string IrradiatedSupercritical {
            get {
                return ResourceManager.GetString("IrradiatedSupercritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned Paradise (Lush).
        /// </summary>
        public static string LushAbandonedParadise {
            get {
                return ResourceManager.GetString("LushAbandonedParadise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bountiful (Lush).
        /// </summary>
        public static string LushBountiful {
            get {
                return ResourceManager.GetString("LushBountiful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flourishing (Lush).
        /// </summary>
        public static string LushFlourishing {
            get {
                return ResourceManager.GetString("LushFlourishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grassy (Lush).
        /// </summary>
        public static string LushGrassy {
            get {
                return ResourceManager.GetString("LushGrassy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humid (Lush).
        /// </summary>
        public static string LushHumid {
            get {
                return ResourceManager.GetString("LushHumid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infected Paradise (Lush).
        /// </summary>
        public static string LushInfectedParadise {
            get {
                return ResourceManager.GetString("LushInfectedParadise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infested Paradise (Lush).
        /// </summary>
        public static string LushInfestedParadise {
            get {
                return ResourceManager.GetString("LushInfestedParadise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overgrown (Lush).
        /// </summary>
        public static string LushOvergrown {
            get {
                return ResourceManager.GetString("LushOvergrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overgrown Relic (Lush).
        /// </summary>
        public static string LushOvergrownRelic {
            get {
                return ResourceManager.GetString("LushOvergrownRelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paradise (Lush).
        /// </summary>
        public static string LushParadise {
            get {
                return ResourceManager.GetString("LushParadise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainy (Lush).
        /// </summary>
        public static string LushRainy {
            get {
                return ResourceManager.GetString("LushRainy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperate (Lush).
        /// </summary>
        public static string LushTemperate {
            get {
                return ResourceManager.GetString("LushTemperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nest (Lush).
        /// </summary>
        public static string LushTheNest {
            get {
                return ResourceManager.GetString("LushTheNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reliquary (Lush).
        /// </summary>
        public static string LushTheReliquary {
            get {
                return ResourceManager.GetString("LushTheReliquary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical (Lush).
        /// </summary>
        public static string LushTropical {
            get {
                return ResourceManager.GetString("LushTropical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdant (Lush).
        /// </summary>
        public static string LushVerdant {
            get {
                return ResourceManager.GetString("LushVerdant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viridescent (Lush).
        /// </summary>
        public static string LushViridescent {
            get {
                return ResourceManager.GetString("LushViridescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worm-ridden (Lush).
        /// </summary>
        public static string LushWormRidden {
            get {
                return ResourceManager.GetString("LushWormRidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xeno-Colony (Lush).
        /// </summary>
        public static string LushXenoColony {
            get {
                return ResourceManager.GetString("LushXenoColony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boggy (Marsh).
        /// </summary>
        public static string MarshBoggy {
            get {
                return ResourceManager.GetString("MarshBoggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy (Marsh).
        /// </summary>
        public static string MarshCloudy {
            get {
                return ResourceManager.GetString("MarshCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damp (Marsh).
        /// </summary>
        public static string MarshDamp {
            get {
                return ResourceManager.GetString("MarshDamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endless Morass (Marsh).
        /// </summary>
        public static string MarshEndlessMorass {
            get {
                return ResourceManager.GetString("MarshEndlessMorass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foggy (Marsh).
        /// </summary>
        public static string MarshFoggy {
            get {
                return ResourceManager.GetString("MarshFoggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazy (Marsh).
        /// </summary>
        public static string MarshHazy {
            get {
                return ResourceManager.GetString("MarshHazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshy (Marsh).
        /// </summary>
        public static string MarshMarshy {
            get {
                return ResourceManager.GetString("MarshMarshy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misty (Marsh).
        /// </summary>
        public static string MarshMisty {
            get {
                return ResourceManager.GetString("MarshMisty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murky (Marsh).
        /// </summary>
        public static string MarshMurky {
            get {
                return ResourceManager.GetString("MarshMurky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quagmire (Marsh).
        /// </summary>
        public static string MarshQuagmire {
            get {
                return ResourceManager.GetString("MarshQuagmire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reeking (Marsh).
        /// </summary>
        public static string MarshReeking {
            get {
                return ResourceManager.GetString("MarshReeking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swamp (Marsh).
        /// </summary>
        public static string MarshSwamp {
            get {
                return ResourceManager.GetString("MarshSwamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical (Marsh).
        /// </summary>
        public static string MarshTropical {
            get {
                return ResourceManager.GetString("MarshTropical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapour (Marsh).
        /// </summary>
        public static string MarshVapour {
            get {
                return ResourceManager.GetString("MarshVapour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure (Mega Exotic).
        /// </summary>
        public static string MegaExoticAzure {
            get {
                return ResourceManager.GetString("MegaExoticAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood (Mega Exotic).
        /// </summary>
        public static string MegaExoticBlood {
            get {
                return ResourceManager.GetString("MegaExoticBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean (Mega Exotic).
        /// </summary>
        public static string MegaExoticCerulean {
            get {
                return ResourceManager.GetString("MegaExoticCerulean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromatic Fog (Mega Exotic).
        /// </summary>
        public static string MegaExoticChromaticFog {
            get {
                return ResourceManager.GetString("MegaExoticChromaticFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson (Mega Exotic).
        /// </summary>
        public static string MegaExoticCrimson {
            get {
                return ResourceManager.GetString("MegaExoticCrimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathly Green Anomaly (Mega Exotic).
        /// </summary>
        public static string MegaExoticDeathlyGreenAnomaly {
            get {
                return ResourceManager.GetString("MegaExoticDeathlyGreenAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doomed Jade (Mega Exotic).
        /// </summary>
        public static string MegaExoticDoomedJade {
            get {
                return ResourceManager.GetString("MegaExoticDoomedJade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen Anomaly (Mega Exotic).
        /// </summary>
        public static string MegaExoticFrozenAnomaly {
            get {
                return ResourceManager.GetString("MegaExoticFrozenAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harsh Blue Globe (Mega Exotic).
        /// </summary>
        public static string MegaExoticHarshBlueGlobe {
            get {
                return ResourceManager.GetString("MegaExoticHarshBlueGlobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haunted Emeril (Mega Exotic).
        /// </summary>
        public static string MegaExoticHauntedEmeril {
            get {
                return ResourceManager.GetString("MegaExoticHauntedEmeril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Blue (Mega Exotic).
        /// </summary>
        public static string MegaExoticLostBlue {
            get {
                return ResourceManager.GetString("MegaExoticLostBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Green (Mega Exotic).
        /// </summary>
        public static string MegaExoticLostGreen {
            get {
                return ResourceManager.GetString("MegaExoticLostGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Red (Mega Exotic).
        /// </summary>
        public static string MegaExoticLostRed {
            get {
                return ResourceManager.GetString("MegaExoticLostRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planetary Anomaly (Mega Exotic).
        /// </summary>
        public static string MegaExoticPlanetaryAnomaly {
            get {
                return ResourceManager.GetString("MegaExoticPlanetaryAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [REDACTED] (Mega Exotic).
        /// </summary>
        public static string MegaExoticRedacted {
            get {
                return ResourceManager.GetString("MegaExoticRedacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarlet (Mega Exotic).
        /// </summary>
        public static string MegaExoticScarlet {
            get {
                return ResourceManager.GetString("MegaExoticScarlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellar Corruption Detected (Mega Exotic).
        /// </summary>
        public static string MegaExoticStellarCorruptionDetected {
            get {
                return ResourceManager.GetString("MegaExoticStellarCorruptionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Anomaly (Mega Exotic).
        /// </summary>
        public static string MegaExoticToxicAnomaly {
            get {
                return ResourceManager.GetString("MegaExoticToxicAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultramarine (Mega Exotic).
        /// </summary>
        public static string MegaExoticUltramarine {
            get {
                return ResourceManager.GetString("MegaExoticUltramarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vermillion Globe (Mega Exotic).
        /// </summary>
        public static string MegaExoticVermillionGlobe {
            get {
                return ResourceManager.GetString("MegaExoticVermillionGlobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vile Anomaly (Mega Exotic).
        /// </summary>
        public static string MegaExoticVileAnomaly {
            get {
                return ResourceManager.GetString("MegaExoticVileAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine Dark (Mega Exotic).
        /// </summary>
        public static string MegaExoticWineDark {
            get {
                return ResourceManager.GetString("MegaExoticWineDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arid (Scorched).
        /// </summary>
        public static string ScorchedArid {
            get {
                return ResourceManager.GetString("ScorchedArid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiling (Scorched).
        /// </summary>
        public static string ScorchedBoiling {
            get {
                return ResourceManager.GetString("ScorchedBoiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiling Doom (Scorched).
        /// </summary>
        public static string ScorchedBoilingDoom {
            get {
                return ResourceManager.GetString("ScorchedBoilingDoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charred (Scorched).
        /// </summary>
        public static string ScorchedCharred {
            get {
                return ResourceManager.GetString("ScorchedCharred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted (Scorched).
        /// </summary>
        public static string ScorchedCorrupted {
            get {
                return ResourceManager.GetString("ScorchedCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiery (Scorched).
        /// </summary>
        public static string ScorchedFiery {
            get {
                return ResourceManager.GetString("ScorchedFiery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiery Dreadworld (Scorched).
        /// </summary>
        public static string ScorchedFieryDreadworld {
            get {
                return ResourceManager.GetString("ScorchedFieryDreadworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Temperature (Scorched).
        /// </summary>
        public static string ScorchedHighTemperature {
            get {
                return ResourceManager.GetString("ScorchedHighTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot (Scorched).
        /// </summary>
        public static string ScorchedHot {
            get {
                return ResourceManager.GetString("ScorchedHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incandescent (Scorched).
        /// </summary>
        public static string ScorchedIncandescent {
            get {
                return ResourceManager.GetString("ScorchedIncandescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infested (Scorched).
        /// </summary>
        public static string ScorchedInfested {
            get {
                return ResourceManager.GetString("ScorchedInfested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalding (Scorched).
        /// </summary>
        public static string ScorchedScalding {
            get {
                return ResourceManager.GetString("ScorchedScalding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorched (Scorched).
        /// </summary>
        public static string ScorchedScorched {
            get {
                return ResourceManager.GetString("ScorchedScorched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorched Relic (Scorched).
        /// </summary>
        public static string ScorchedScorchedRelic {
            get {
                return ResourceManager.GetString("ScorchedScorchedRelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrid (Scorched).
        /// </summary>
        public static string ScorchedTorrid {
            get {
                return ResourceManager.GetString("ScorchedTorrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acidic (Toxic).
        /// </summary>
        public static string ToxicAcidic {
            get {
                return ResourceManager.GetString("ToxicAcidic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrid (Toxic).
        /// </summary>
        public static string ToxicAcrid {
            get {
                return ResourceManager.GetString("ToxicAcrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blighted (Toxic).
        /// </summary>
        public static string ToxicBlighted {
            get {
                return ResourceManager.GetString("ToxicBlighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caustic (Toxic).
        /// </summary>
        public static string ToxicCaustic {
            get {
                return ResourceManager.GetString("ToxicCaustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caustic Nightmare (Toxic).
        /// </summary>
        public static string ToxicCausticNightmare {
            get {
                return ResourceManager.GetString("ToxicCausticNightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrosive (Toxic).
        /// </summary>
        public static string ToxicCorrosive {
            get {
                return ResourceManager.GetString("ToxicCorrosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decaying Ruin (Toxic).
        /// </summary>
        public static string ToxicDecayingRuin {
            get {
                return ResourceManager.GetString("ToxicDecayingRuin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infested (Toxic).
        /// </summary>
        public static string ToxicInfested {
            get {
                return ResourceManager.GetString("ToxicInfested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasmatic (Toxic).
        /// </summary>
        public static string ToxicMiasmatic {
            get {
                return ResourceManager.GetString("ToxicMiasmatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noxious (Toxic).
        /// </summary>
        public static string ToxicNoxious {
            get {
                return ResourceManager.GetString("ToxicNoxious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poisonous (Toxic).
        /// </summary>
        public static string ToxicPoisonous {
            get {
                return ResourceManager.GetString("ToxicPoisonous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotting (Toxic).
        /// </summary>
        public static string ToxicRotting {
            get {
                return ResourceManager.GetString("ToxicRotting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic (Toxic).
        /// </summary>
        public static string ToxicToxic {
            get {
                return ResourceManager.GetString("ToxicToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Horror (Toxic).
        /// </summary>
        public static string ToxicToxicHorror {
            get {
                return ResourceManager.GetString("ToxicToxicHorror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashen (Volcanic).
        /// </summary>
        public static string VolcanicAshen {
            get {
                return ResourceManager.GetString("VolcanicAshen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ash-Shrouded (Volcanic).
        /// </summary>
        public static string VolcanicAshShrouded {
            get {
                return ResourceManager.GetString("VolcanicAshShrouded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basalt (Volcanic).
        /// </summary>
        public static string VolcanicBasalt {
            get {
                return ResourceManager.GetString("VolcanicBasalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erupting (Volcanic).
        /// </summary>
        public static string VolcanicErupting {
            get {
                return ResourceManager.GetString("VolcanicErupting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame-Ruptured (Volcanic).
        /// </summary>
        public static string VolcanicFlameRuptured {
            get {
                return ResourceManager.GetString("VolcanicFlameRuptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imminent Core Detonation (Volcanic).
        /// </summary>
        public static string VolcanicImminentCoreDetonation {
            get {
                return ResourceManager.GetString("VolcanicImminentCoreDetonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lava (Volcanic).
        /// </summary>
        public static string VolcanicLava {
            get {
                return ResourceManager.GetString("VolcanicLava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magma (Volcanic).
        /// </summary>
        public static string VolcanicMagma {
            get {
                return ResourceManager.GetString("VolcanicMagma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molten (Volcanic).
        /// </summary>
        public static string VolcanicMolten {
            get {
                return ResourceManager.GetString("VolcanicMolten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian Bead (Volcanic).
        /// </summary>
        public static string VolcanicObsidianBead {
            get {
                return ResourceManager.GetString("VolcanicObsidianBead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tectonic (Volcanic).
        /// </summary>
        public static string VolcanicTectonic {
            get {
                return ResourceManager.GetString("VolcanicTectonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable (Volcanic).
        /// </summary>
        public static string VolcanicUnstable {
            get {
                return ResourceManager.GetString("VolcanicUnstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violent (Volcanic).
        /// </summary>
        public static string VolcanicViolent {
            get {
                return ResourceManager.GetString("VolcanicViolent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcanic (Volcanic).
        /// </summary>
        public static string VolcanicVolcanic {
            get {
                return ResourceManager.GetString("VolcanicVolcanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatic (Waterworld).
        /// </summary>
        public static string WaterworldAquatic {
            get {
                return ResourceManager.GetString("WaterworldAquatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine (Waterworld).
        /// </summary>
        public static string WaterworldMarine {
            get {
                return ResourceManager.GetString("WaterworldMarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultramarine Giant (Waterworld).
        /// </summary>
        public static string WaterworldUltramarineGiant {
            get {
                return ResourceManager.GetString("WaterworldUltramarineGiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterlocked (Waterworld).
        /// </summary>
        public static string WaterworldWaterlocked {
            get {
                return ResourceManager.GetString("WaterworldWaterlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterworld (Waterworld).
        /// </summary>
        public static string WaterworldWaterworld {
            get {
                return ResourceManager.GetString("WaterworldWaterworld", resourceCulture);
            }
        }
    }
}
