//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaunaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaunaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.FaunaResource", typeof(FaunaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Notes.
        /// </summary>
        public static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour Type.
        /// </summary>
        public static string BehaviourType {
            get {
                return ResourceManager.GetString("BehaviourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilized.
        /// </summary>
        public static string CivilizedBy {
            get {
                return ResourceManager.GetString("CivilizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Type.
        /// </summary>
        public static string DietType {
            get {
                return ResourceManager.GetString("DietType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered.
        /// </summary>
        public static string DiscoveredBy {
            get {
                return ResourceManager.GetString("DiscoveredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered Date.
        /// </summary>
        public static string DiscoveredDate {
            get {
                return ResourceManager.GetString("DiscoveredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered Link on Wiki.
        /// </summary>
        public static string DiscoveredLinkOnWiki {
            get {
                return ResourceManager.GetString("DiscoveredLinkOnWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Menu.
        /// </summary>
        public static string DiscoveryMenu {
            get {
                return ResourceManager.GetString("DiscoveryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Platform.
        /// </summary>
        public static string DiscoveryPlatform {
            get {
                return ResourceManager.GetString("DiscoveryPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Screen Height.
        /// </summary>
        public static string DiscoveryScreenHeight {
            get {
                return ResourceManager.GetString("DiscoveryScreenHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Screen Weight.
        /// </summary>
        public static string DiscoveryScreenWeight {
            get {
                return ResourceManager.GetString("DiscoveryScreenWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extinction Status?.
        /// </summary>
        public static string ExtinctionStatus {
            get {
                return ResourceManager.GetString("ExtinctionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender 1.
        /// </summary>
        public static string Gender1 {
            get {
                return ResourceManager.GetString("Gender1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender 1 Scan Max Height (m).
        /// </summary>
        public static string Gender1ScanMaxHeight {
            get {
                return ResourceManager.GetString("Gender1ScanMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender 1 Scan Max Weight (kg).
        /// </summary>
        public static string Gender1ScanMaxWeight {
            get {
                return ResourceManager.GetString("Gender1ScanMaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender 2.
        /// </summary>
        public static string Gender2 {
            get {
                return ResourceManager.GetString("Gender2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender 2 scan Max Height (m).
        /// </summary>
        public static string Gender2ScanMaxHeight {
            get {
                return ResourceManager.GetString("Gender2ScanMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender 2 Scan Max Weight (kg).
        /// </summary>
        public static string Gender2ScanMaxWeight {
            get {
                return ResourceManager.GetString("Gender2ScanMaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genus Subtype.
        /// </summary>
        public static string GenusSubtype {
            get {
                return ResourceManager.GetString("GenusSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Date PC.
        /// </summary>
        public static string LegacyFaunaDatePC {
            get {
                return ResourceManager.GetString("LegacyFaunaDatePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Date PS.
        /// </summary>
        public static string LegacyFaunaDatePS {
            get {
                return ResourceManager.GetString("LegacyFaunaDatePS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Date Xbox.
        /// </summary>
        public static string LegacyFaunaDateXbox {
            get {
                return ResourceManager.GetString("LegacyFaunaDateXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Discoverer PC.
        /// </summary>
        public static string LegacyFaunaDiscovererPC {
            get {
                return ResourceManager.GetString("LegacyFaunaDiscovererPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Discoverer PS.
        /// </summary>
        public static string LegacyFaunaDiscovererPS {
            get {
                return ResourceManager.GetString("LegacyFaunaDiscovererPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Discoverer XBox.
        /// </summary>
        public static string LegacyFaunaDiscovererXbox {
            get {
                return ResourceManager.GetString("LegacyFaunaDiscovererXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Name PC.
        /// </summary>
        public static string LegacyFaunaNamePC {
            get {
                return ResourceManager.GetString("LegacyFaunaNamePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Name PS.
        /// </summary>
        public static string LegacyFaunaNamePS {
            get {
                return ResourceManager.GetString("LegacyFaunaNamePS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Fauna Name Xbox.
        /// </summary>
        public static string LegacyFaunaNameXbox {
            get {
                return ResourceManager.GetString("LegacyFaunaNameXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Notes.
        /// </summary>
        public static string LocationNotes {
            get {
                return ResourceManager.GetString("LocationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fauna (unique name key).
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fauna Name (Integrated Name after Expeditions).
        /// </summary>
        public static string NameAfterExpeditions {
            get {
                return ResourceManager.GetString("NameAfterExpeditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMS Wiki Link.
        /// </summary>
        public static string NMSWikiLink {
            get {
                return ResourceManager.GetString("NMSWikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fauna Name (Original).
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Team.
        /// </summary>
        public static string ResearchTeam {
            get {
                return ResourceManager.GetString("ResearchTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Notes.
        /// </summary>
        public static string SummaryNotes {
            get {
                return ResourceManager.GetString("SummaryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Release.
        /// </summary>
        public static string VersionRelease {
            get {
                return ResourceManager.GetString("VersionRelease", resourceCulture);
            }
        }
    }
}
