//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaterialsResourceType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaterialsResourceType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.MaterialsResourceType", typeof(MaterialsResourceType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Cadmium.
        /// </summary>
        public static string ActivatedCadmium {
            get {
                return ResourceManager.GetString("ActivatedCadmium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Copper.
        /// </summary>
        public static string ActivatedCopper {
            get {
                return ResourceManager.GetString("ActivatedCopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Emeril.
        /// </summary>
        public static string ActivatedEmeril {
            get {
                return ResourceManager.GetString("ActivatedEmeril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Indium.
        /// </summary>
        public static string ActivatedIndium {
            get {
                return ResourceManager.GetString("ActivatedIndium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Quartzite.
        /// </summary>
        public static string ActivatedQuartzite {
            get {
                return ResourceManager.GetString("ActivatedQuartzite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albumen Pear lOrb.
        /// </summary>
        public static string AlbumenPearlOrb {
            get {
                return ResourceManager.GetString("AlbumenPearlOrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cactus Flesh.
        /// </summary>
        public static string CactusFlesh {
            get {
                return ResourceManager.GetString("CactusFlesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromatic Metal.
        /// </summary>
        public static string ChromaticMetal {
            get {
                return ResourceManager.GetString("ChromaticMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condensed Carbon.
        /// </summary>
        public static string CondensedCarbon {
            get {
                return ResourceManager.GetString("CondensedCarbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature Egg.
        /// </summary>
        public static string CreatureEgg {
            get {
                return ResourceManager.GetString("CreatureEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystallised Helium.
        /// </summary>
        public static string CrystallisedHelium {
            get {
                return ResourceManager.GetString("CrystallisedHelium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Sulphide.
        /// </summary>
        public static string CrystalSulphide {
            get {
                return ResourceManager.GetString("CrystalSulphide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursed Dust.
        /// </summary>
        public static string CursedDust {
            get {
                return ResourceManager.GetString("CursedDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyto-Phosphate.
        /// </summary>
        public static string CytoPhosphate {
            get {
                return ResourceManager.GetString("CytoPhosphate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di-hydrogen.
        /// </summary>
        public static string Dihydrogen {
            get {
                return ResourceManager.GetString("Dihydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferrite Dust.
        /// </summary>
        public static string FerriteDust {
            get {
                return ResourceManager.GetString("FerriteDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Crystal.
        /// </summary>
        public static string FloatingCrystal {
            get {
                return ResourceManager.GetString("FloatingCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost Crystal.
        /// </summary>
        public static string FrostCrystal {
            get {
                return ResourceManager.GetString("FrostCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fungal Mould.
        /// </summary>
        public static string FungalMould {
            get {
                return ResourceManager.GetString("FungalMould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma Root.
        /// </summary>
        public static string GammaRoot {
            get {
                return ResourceManager.GetString("GammaRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitino Ball.
        /// </summary>
        public static string GravitinoBall {
            get {
                return ResourceManager.GetString("GravitinoBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humming Sac.
        /// </summary>
        public static string HummingSac {
            get {
                return ResourceManager.GetString("HummingSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ionised Cobalt.
        /// </summary>
        public static string IonisedCobalt {
            get {
                return ResourceManager.GetString("IonisedCobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelp Sac.
        /// </summary>
        public static string KelpSac {
            get {
                return ResourceManager.GetString("KelpSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Pearl.
        /// </summary>
        public static string LivingPearl {
            get {
                return ResourceManager.GetString("LivingPearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Slime.
        /// </summary>
        public static string LivingSlime {
            get {
                return ResourceManager.GetString("LivingSlime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetised Ferrite.
        /// </summary>
        public static string MagnetisedFerrite {
            get {
                return ResourceManager.GetString("MagnetisedFerrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marrow Bulb.
        /// </summary>
        public static string MarrowBulb {
            get {
                return ResourceManager.GetString("MarrowBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel.
        /// </summary>
        public static string Nickel {
            get {
                return ResourceManager.GetString("Nickel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure Ferrite.
        /// </summary>
        public static string PureFerrite {
            get {
                return ResourceManager.GetString("PureFerrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual Goop.
        /// </summary>
        public static string ResidualGoop {
            get {
                return ResourceManager.GetString("ResidualGoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runaway Mould.
        /// </summary>
        public static string RunawayMould {
            get {
                return ResourceManager.GetString("RunawayMould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rusted Metal.
        /// </summary>
        public static string RustedMetal {
            get {
                return ResourceManager.GetString("RustedMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sac Venom.
        /// </summary>
        public static string SacVenom {
            get {
                return ResourceManager.GetString("SacVenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentient Plant.
        /// </summary>
        public static string SentientPlant {
            get {
                return ResourceManager.GetString("SentientPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silicate Powder.
        /// </summary>
        public static string SilicatePowder {
            get {
                return ResourceManager.GetString("SilicatePowder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium Nitrate.
        /// </summary>
        public static string SodiumNitrate {
            get {
                return ResourceManager.GetString("SodiumNitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Bulb.
        /// </summary>
        public static string StarBulb {
            get {
                return ResourceManager.GetString("StarBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm Crystal.
        /// </summary>
        public static string StormCrystal {
            get {
                return ResourceManager.GetString("StormCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viscous Fluids.
        /// </summary>
        public static string ViscousFluids {
            get {
                return ResourceManager.GetString("ViscousFluids", resourceCulture);
            }
        }
    }
}
