//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiToolResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiToolResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.MultiToolResource", typeof(MultiToolResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Acquistion Guidance.
        /// </summary>
        public static string AcquistionGuidance {
            get {
                return ResourceManager.GetString("AcquistionGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Civilized.
        /// </summary>
        public static string CivilizedBy {
            get {
                return ResourceManager.GetString("CivilizedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discovered.
        /// </summary>
        public static string DiscoveredBy {
            get {
                return ResourceManager.GetString("DiscoveredBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discovered Link on Wiki.
        /// </summary>
        public static string DiscoveredLinkOnWiki {
            get {
                return ResourceManager.GetString("DiscoveredLinkOnWiki", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discovery Date.
        /// </summary>
        public static string DiscoveryDate {
            get {
                return ResourceManager.GetString("DiscoveryDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Document Sequence.
        /// </summary>
        public static string DocumentSequence {
            get {
                return ResourceManager.GetString("DocumentSequence", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crystals.
        /// </summary>
        public static string HasCrystals {
            get {
                return ResourceManager.GetString("HasCrystals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Glowtubes.
        /// </summary>
        public static string HasGlowtubes {
            get {
                return ResourceManager.GetString("HasGlowtubes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Horns.
        /// </summary>
        public static string HasHorns {
            get {
                return ResourceManager.GetString("HasHorns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name of MT.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primary Color.
        /// </summary>
        public static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Research Team.
        /// </summary>
        public static string ResearchTeam {
            get {
                return ResourceManager.GetString("ResearchTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secondary Color.
        /// </summary>
        public static string SecondaryColor {
            get {
                return ResourceManager.GetString("SecondaryColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Notes.
        /// </summary>
        public static string UserNotes {
            get {
                return ResourceManager.GetString("UserNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wiki Link.
        /// </summary>
        public static string WikiLink {
            get {
                return ResourceManager.GetString("WikiLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XX (second cord).
        /// </summary>
        public static string XXSecondCoordinate {
            get {
                return ResourceManager.GetString("XXSecondCoordinate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YY (first coord).
        /// </summary>
        public static string YYFirstCoordinate {
            get {
                return ResourceManager.GetString("YYFirstCoordinate", resourceCulture);
            }
        }
    }
}
