//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MultiToolColorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiToolColorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.MultiToolColorResource", typeof(MultiToolColorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua Green.
        /// </summary>
        internal static string AquaGreen {
            get {
                return ResourceManager.GetString("AquaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctic White.
        /// </summary>
        internal static string ArcticWhite {
            get {
                return ResourceManager.GetString("ArcticWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Green.
        /// </summary>
        internal static string BlueGreen {
            get {
                return ResourceManager.GetString("BlueGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Yellow.
        /// </summary>
        internal static string BronzeYellow {
            get {
                return ResourceManager.GetString("BronzeYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble Gum.
        /// </summary>
        internal static string BubbleGum {
            get {
                return ResourceManager.GetString("BubbleGum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burnt Orange.
        /// </summary>
        internal static string BurntOrange {
            get {
                return ResourceManager.GetString("BurntOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt Blue.
        /// </summary>
        internal static string CobaltBlue {
            get {
                return ResourceManager.GetString("CobaltBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Grey.
        /// </summary>
        internal static string CoolGrey {
            get {
                return ResourceManager.GetString("CoolGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson Red.
        /// </summary>
        internal static string CrimsonRed {
            get {
                return ResourceManager.GetString("CrimsonRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curry Yellow.
        /// </summary>
        internal static string CurryYellow {
            get {
                return ResourceManager.GetString("CurryYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Brown.
        /// </summary>
        internal static string DarkBrown {
            get {
                return ResourceManager.GetString("DarkBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Magenta.
        /// </summary>
        internal static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Orange.
        /// </summary>
        internal static string DarkOrange {
            get {
                return ResourceManager.GetString("DarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Purple.
        /// </summary>
        internal static string DarkPurple {
            get {
                return ResourceManager.GetString("DarkPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusty Pink.
        /// </summary>
        internal static string DustyPink {
            get {
                return ResourceManager.GetString("DustyPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Green.
        /// </summary>
        internal static string ForestGreen {
            get {
                return ResourceManager.GetString("ForestGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunmetal Blue.
        /// </summary>
        internal static string GunmetalBlue {
            get {
                return ResourceManager.GetString("GunmetalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunmetal Grey.
        /// </summary>
        internal static string GunmetalGrey {
            get {
                return ResourceManager.GetString("GunmetalGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Gold.
        /// </summary>
        internal static string HarvestGold {
            get {
                return ResourceManager.GetString("HarvestGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Pink.
        /// </summary>
        internal static string HotPink {
            get {
                return ResourceManager.GetString("HotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter Green.
        /// </summary>
        internal static string HunterGreen {
            get {
                return ResourceManager.GetString("HunterGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jade Green.
        /// </summary>
        internal static string JadeGreen {
            get {
                return ResourceManager.GetString("JadeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon Yellow.
        /// </summary>
        internal static string LemonYellow {
            get {
                return ResourceManager.GetString("LemonYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blue.
        /// </summary>
        internal static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Brown.
        /// </summary>
        internal static string LightBrown {
            get {
                return ResourceManager.GetString("LightBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Green.
        /// </summary>
        internal static string LightGreen {
            get {
                return ResourceManager.GetString("LightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Orange.
        /// </summary>
        internal static string LightOrange {
            get {
                return ResourceManager.GetString("LightOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Yellow.
        /// </summary>
        internal static string LightYellow {
            get {
                return ResourceManager.GetString("LightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime Green.
        /// </summary>
        internal static string LimeGreen {
            get {
                return ResourceManager.GetString("LimeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic Blue.
        /// </summary>
        internal static string MetallicBlue {
            get {
                return ResourceManager.GetString("MetallicBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic Bronze.
        /// </summary>
        internal static string MetallicBronze {
            get {
                return ResourceManager.GetString("MetallicBronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic Copper.
        /// </summary>
        internal static string MetallicCopper {
            get {
                return ResourceManager.GetString("MetallicCopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mocha Brown.
        /// </summary>
        internal static string MochaBrown {
            get {
                return ResourceManager.GetString("MochaBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moss Green.
        /// </summary>
        internal static string MossGreen {
            get {
                return ResourceManager.GetString("MossGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy Blue.
        /// </summary>
        internal static string NavyBlue {
            get {
                return ResourceManager.GetString("NavyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neon Green.
        /// </summary>
        internal static string NeonGreen {
            get {
                return ResourceManager.GetString("NeonGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocher Brown.
        /// </summary>
        internal static string OcherBrown {
            get {
                return ResourceManager.GetString("OcherBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Rose.
        /// </summary>
        internal static string PaleRose {
            get {
                return ResourceManager.GetString("PaleRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pine Green.
        /// </summary>
        internal static string PineGreen {
            get {
                return ResourceManager.GetString("PineGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Orange.
        /// </summary>
        internal static string RedOrange {
            get {
                return ResourceManager.GetString("RedOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rose Gold.
        /// </summary>
        internal static string RoseGold {
            get {
                return ResourceManager.GetString("RoseGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Blue.
        /// </summary>
        internal static string RoyalBlue {
            get {
                return ResourceManager.GetString("RoyalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby Red.
        /// </summary>
        internal static string RubyRed {
            get {
                return ResourceManager.GetString("RubyRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarlet Red.
        /// </summary>
        internal static string ScarletRed {
            get {
                return ResourceManager.GetString("ScarletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Blue.
        /// </summary>
        internal static string SkyBlue {
            get {
                return ResourceManager.GetString("SkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Green.
        /// </summary>
        internal static string StoneGreen {
            get {
                return ResourceManager.GetString("StoneGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista Blue.
        /// </summary>
        internal static string VistaBlue {
            get {
                return ResourceManager.GetString("VistaBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Grey.
        /// </summary>
        internal static string WarmGrey {
            get {
                return ResourceManager.GetString("WarmGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Green.
        /// </summary>
        internal static string YellowGreen {
            get {
                return ResourceManager.GetString("YellowGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Orange.
        /// </summary>
        internal static string YellowOrange {
            get {
                return ResourceManager.GetString("YellowOrange", resourceCulture);
            }
        }
    }
}
