//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiToolResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiToolResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.MultiToolResource", typeof(MultiToolResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Muzzle.
        /// </summary>
        public static string AngleMuzzle {
            get {
                return ResourceManager.GetString("AngleMuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Blaze.
        /// </summary>
        public static string CircleBlaze {
            get {
                return ResourceManager.GetString("CircleBlaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hose Muzzle.
        /// </summary>
        public static string HoseMuzzle {
            get {
                return ResourceManager.GetString("HoseMuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Gun.
        /// </summary>
        public static string RailGun {
            get {
                return ResourceManager.GetString("RailGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starter Pistol.
        /// </summary>
        public static string StarterPistol {
            get {
                return ResourceManager.GetString("StarterPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltaic Staff.
        /// </summary>
        public static string VoltaicStaff {
            get {
                return ResourceManager.GetString("VoltaicStaff", resourceCulture);
            }
        }
    }
}
