//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanetAtmosphereColorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanetAtmosphereColorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.PlanetAtmosphereColorResource", typeof(PlanetAtmosphereColorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apricot.
        /// </summary>
        public static string Apricot {
            get {
                return ResourceManager.GetString("Apricot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue green.
        /// </summary>
        public static string Bluegreen {
            get {
                return ResourceManager.GetString("Bluegreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue grey.
        /// </summary>
        public static string Bluegrey {
            get {
                return ResourceManager.GetString("Bluegrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue violet.
        /// </summary>
        public static string Blueviolet {
            get {
                return ResourceManager.GetString("Blueviolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnation pink.
        /// </summary>
        public static string Carnationpink {
            get {
                return ResourceManager.GetString("Carnationpink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerulean.
        /// </summary>
        public static string Cerulean {
            get {
                return ResourceManager.GetString("Cerulean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dandelion.
        /// </summary>
        public static string Dandelion {
            get {
                return ResourceManager.GetString("Dandelion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green yellow.
        /// </summary>
        public static string Greenyellow {
            get {
                return ResourceManager.GetString("Greenyellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        public static string Grey {
            get {
                return ResourceManager.GetString("Grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome.
        /// </summary>
        public static string Monochrome {
            get {
                return ResourceManager.GetString("Monochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome blue.
        /// </summary>
        public static string Monochromeblue {
            get {
                return ResourceManager.GetString("Monochromeblue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome green.
        /// </summary>
        public static string Monochromegreen {
            get {
                return ResourceManager.GetString("Monochromegreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome orange.
        /// </summary>
        public static string Monochromeorange {
            get {
                return ResourceManager.GetString("Monochromeorange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome red.
        /// </summary>
        public static string Monochromered {
            get {
                return ResourceManager.GetString("Monochromered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome yellow.
        /// </summary>
        public static string Monochromeyellow {
            get {
                return ResourceManager.GetString("Monochromeyellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red orange.
        /// </summary>
        public static string Redorange {
            get {
                return ResourceManager.GetString("Redorange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red violet.
        /// </summary>
        public static string Redviolet {
            get {
                return ResourceManager.GetString("Redviolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarlet.
        /// </summary>
        public static string Scarlet {
            get {
                return ResourceManager.GetString("Scarlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        public static string Violet {
            get {
                return ResourceManager.GetString("Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet red.
        /// </summary>
        public static string Violetred {
            get {
                return ResourceManager.GetString("Violetred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow green.
        /// </summary>
        public static string Yellowgreen {
            get {
                return ResourceManager.GetString("Yellowgreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow orange.
        /// </summary>
        public static string Yelloworange {
            get {
                return ResourceManager.GetString("Yelloworange", resourceCulture);
            }
        }
    }
}
