//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanetResourceItemsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanetResourceItemsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.PlanetResourceItemsResource", typeof(PlanetResourceItemsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Cadmium.
        /// </summary>
        public static string ActivatedCadmium {
            get {
                return ResourceManager.GetString("ActivatedCadmium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Copper.
        /// </summary>
        public static string ActivatedCopper {
            get {
                return ResourceManager.GetString("ActivatedCopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Emeril.
        /// </summary>
        public static string ActivatedEmeril {
            get {
                return ResourceManager.GetString("ActivatedEmeril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Indium.
        /// </summary>
        public static string ActivatedIndium {
            get {
                return ResourceManager.GetString("ActivatedIndium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Quartzite.
        /// </summary>
        public static string ActivatedQuartzite {
            get {
                return ResourceManager.GetString("ActivatedQuartzite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminium.
        /// </summary>
        public static string Aluminium {
            get {
                return ResourceManager.GetString("Aluminium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammonia.
        /// </summary>
        public static string Ammonia {
            get {
                return ResourceManager.GetString("Ammonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basalt.
        /// </summary>
        public static string Basalt {
            get {
                return ResourceManager.GetString("Basalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cactus Flesh.
        /// </summary>
        public static string CactusFlesh {
            get {
                return ResourceManager.GetString("CactusFlesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadmium.
        /// </summary>
        public static string Cadmium {
            get {
                return ResourceManager.GetString("Cadmium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon.
        /// </summary>
        public static string Carbon {
            get {
                return ResourceManager.GetString("Carbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorine.
        /// </summary>
        public static string Chlorine {
            get {
                return ResourceManager.GetString("Chlorine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromatic Metal.
        /// </summary>
        public static string ChromaticMetal {
            get {
                return ResourceManager.GetString("ChromaticMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt.
        /// </summary>
        public static string Cobalt {
            get {
                return ResourceManager.GetString("Cobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condensed Carbon.
        /// </summary>
        public static string CondensedCarbon {
            get {
                return ResourceManager.GetString("CondensedCarbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        public static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystallised Helium.
        /// </summary>
        public static string CrystallisedHelium {
            get {
                return ResourceManager.GetString("CrystallisedHelium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursed Dust.
        /// </summary>
        public static string CursedDust {
            get {
                return ResourceManager.GetString("CursedDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyto-Phosphate.
        /// </summary>
        public static string CytoPhosphate {
            get {
                return ResourceManager.GetString("CytoPhosphate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuterium.
        /// </summary>
        public static string Deuterium {
            get {
                return ResourceManager.GetString("Deuterium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di-hydrogen.
        /// </summary>
        public static string Dihydrogen {
            get {
                return ResourceManager.GetString("Dihydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dioxite.
        /// </summary>
        public static string Dioxite {
            get {
                return ResourceManager.GetString("Dioxite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emeril.
        /// </summary>
        public static string Emeril {
            get {
                return ResourceManager.GetString("Emeril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faecium.
        /// </summary>
        public static string Faecium {
            get {
                return ResourceManager.GetString("Faecium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferrite Dust.
        /// </summary>
        public static string FerriteDust {
            get {
                return ResourceManager.GetString("FerriteDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost Crystal.
        /// </summary>
        public static string FrostCrystal {
            get {
                return ResourceManager.GetString("FrostCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fungal Mould.
        /// </summary>
        public static string FungalMould {
            get {
                return ResourceManager.GetString("FungalMould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma Root.
        /// </summary>
        public static string GammaRoot {
            get {
                return ResourceManager.GetString("GammaRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heridium.
        /// </summary>
        public static string Heridium {
            get {
                return ResourceManager.GetString("Heridium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexite.
        /// </summary>
        public static string Hexite {
            get {
                return ResourceManager.GetString("Hexite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indium.
        /// </summary>
        public static string Indium {
            get {
                return ResourceManager.GetString("Indium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ionised Cobalt.
        /// </summary>
        public static string IonisedCobalt {
            get {
                return ResourceManager.GetString("IonisedCobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iridium.
        /// </summary>
        public static string Iridium {
            get {
                return ResourceManager.GetString("Iridium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelp Sac.
        /// </summary>
        public static string KelpSac {
            get {
                return ResourceManager.GetString("KelpSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium.
        /// </summary>
        public static string Lithium {
            get {
                return ResourceManager.GetString("Lithium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Slime.
        /// </summary>
        public static string LivingSlime {
            get {
                return ResourceManager.GetString("LivingSlime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetised Ferrite.
        /// </summary>
        public static string MagnetisedFerrite {
            get {
                return ResourceManager.GetString("MagnetisedFerrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marrow Bulb.
        /// </summary>
        public static string MarrowBulb {
            get {
                return ResourceManager.GetString("MarrowBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mordite.
        /// </summary>
        public static string Mordite {
            get {
                return ResourceManager.GetString("Mordite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel.
        /// </summary>
        public static string Nickel {
            get {
                return ResourceManager.GetString("Nickel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen.
        /// </summary>
        public static string Nitrogen {
            get {
                return ResourceManager.GetString("Nitrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen.
        /// </summary>
        public static string Oxygen {
            get {
                return ResourceManager.GetString("Oxygen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraffinium.
        /// </summary>
        public static string Paraffinium {
            get {
                return ResourceManager.GetString("Paraffinium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorus.
        /// </summary>
        public static string Phosphorus {
            get {
                return ResourceManager.GetString("Phosphorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string Platinum {
            get {
                return ResourceManager.GetString("Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pugneum.
        /// </summary>
        public static string Pugneum {
            get {
                return ResourceManager.GetString("Pugneum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure Ferrite.
        /// </summary>
        public static string PureFerrite {
            get {
                return ResourceManager.GetString("PureFerrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyrite.
        /// </summary>
        public static string Pyrite {
            get {
                return ResourceManager.GetString("Pyrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartzite.
        /// </summary>
        public static string Quartzite {
            get {
                return ResourceManager.GetString("Quartzite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radon.
        /// </summary>
        public static string Radon {
            get {
                return ResourceManager.GetString("Radon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual Goop.
        /// </summary>
        public static string ResidualGoop {
            get {
                return ResourceManager.GetString("ResidualGoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runaway Mould.
        /// </summary>
        public static string RunawayMould {
            get {
                return ResourceManager.GetString("RunawayMould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rusted Metal.
        /// </summary>
        public static string RustedMetal {
            get {
                return ResourceManager.GetString("RustedMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silicate Powder.
        /// </summary>
        public static string SilicatePowder {
            get {
                return ResourceManager.GetString("SilicatePowder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        public static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium Nitrate.
        /// </summary>
        public static string SodiumNitrate {
            get {
                return ResourceManager.GetString("SodiumNitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solanium.
        /// </summary>
        public static string Solanium {
            get {
                return ResourceManager.GetString("Solanium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Bulb.
        /// </summary>
        public static string StarBulb {
            get {
                return ResourceManager.GetString("StarBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulphurine.
        /// </summary>
        public static string Sulphurine {
            get {
                return ResourceManager.GetString("Sulphurine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritium.
        /// </summary>
        public static string Tritium {
            get {
                return ResourceManager.GetString("Tritium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uranium.
        /// </summary>
        public static string Uranium {
            get {
                return ResourceManager.GetString("Uranium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viscous Fluids.
        /// </summary>
        public static string ViscousFluids {
            get {
                return ResourceManager.GetString("ViscousFluids", resourceCulture);
            }
        }
    }
}
