//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettlementResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettlementResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.SettlementResource", typeof(SettlementResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Observed
        ///DD-MMM-YEAR.
        /// </summary>
        public static string DateObserved {
            get {
                return ResourceManager.GetString("DateObserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Release.
        /// </summary>
        public static string GameRelease {
            get {
                return ResourceManager.GetString("GameRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Name (if renamed).
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overseerlink.
        /// </summary>
        public static string OverseerLink {
            get {
                return ResourceManager.GetString("OverseerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor ID.
        /// </summary>
        public static string Surveyor {
            get {
                return ResourceManager.GetString("Surveyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Link.
        /// </summary>
        public static string WikiLink {
            get {
                return ResourceManager.GetString("WikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XX (second coord).
        /// </summary>
        public static string XXSecondCoordinate {
            get {
                return ResourceManager.GetString("XXSecondCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YY (first coord).
        /// </summary>
        public static string YYFirstCoordinate {
            get {
                return ResourceManager.GetString("YYFirstCoordinate", resourceCulture);
            }
        }
    }
}
