//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettlementBuildingTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettlementBuildingTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.SettlementBuildingTypeResource", typeof(SettlementBuildingTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural Unit.
        /// </summary>
        public static string AgriculturalUnit {
            get {
                return ResourceManager.GetString("AgriculturalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Exchange.
        /// </summary>
        public static string CommercialExchange {
            get {
                return ResourceManager.GetString("CommercialExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Repository.
        /// </summary>
        public static string CommercialRepository {
            get {
                return ResourceManager.GetString("CommercialRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coolant Mill.
        /// </summary>
        public static string CoolantMill {
            get {
                return ResourceManager.GetString("CoolantMill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Hall.
        /// </summary>
        public static string DanceHall {
            get {
                return ResourceManager.GetString("DanceHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking Area.
        /// </summary>
        public static string DockingArea {
            get {
                return ResourceManager.GetString("DockingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental Control Unit.
        /// </summary>
        public static string EnvironmentalControlUnit {
            get {
                return ResourceManager.GetString("EnvironmentalControlUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Room.
        /// </summary>
        public static string GeneratorRoom {
            get {
                return ResourceManager.GetString("GeneratorRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Control Unit.
        /// </summary>
        public static string HazardControlUnit {
            get {
                return ResourceManager.GetString("HazardControlUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Hydraulic Wirings.
        /// </summary>
        public static string HydraulicWirings {
            get {
                return ResourceManager.GetString("HydraulicWirings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydro-Silo.
        /// </summary>
        public static string HydroSilo {
            get {
                return ResourceManager.GetString("HydroSilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insalubrious Den.
        /// </summary>
        public static string InsalubriousDen {
            get {
                return ResourceManager.GetString("InsalubriousDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing Area.
        /// </summary>
        public static string LandingArea {
            get {
                return ResourceManager.GetString("LandingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large House.
        /// </summary>
        public static string LargeHouse {
            get {
                return ResourceManager.GetString("LargeHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machinery Unit.
        /// </summary>
        public static string MachineryUnit {
            get {
                return ResourceManager.GetString("MachineryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Unit.
        /// </summary>
        public static string ManufacturingUnit {
            get {
                return ResourceManager.GetString("ManufacturingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Dwelling.
        /// </summary>
        public static string MediumDwelling {
            get {
                return ResourceManager.GetString("MediumDwelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Barn.
        /// </summary>
        public static string MultiBarn {
            get {
                return ResourceManager.GetString("MultiBarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Generator.
        /// </summary>
        public static string PowerGenerator {
            get {
                return ResourceManager.GetString("PowerGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Tower.
        /// </summary>
        public static string ProcessingTower {
            get {
                return ResourceManager.GetString("ProcessingTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Facility.
        /// </summary>
        public static string ProductionFacility {
            get {
                return ResourceManager.GetString("ProductionFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumping Tower.
        /// </summary>
        public static string PumpingTower {
            get {
                return ResourceManager.GetString("PumpingTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Forum.
        /// </summary>
        public static string RetailForum {
            get {
                return ResourceManager.GetString("RetailForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Zone.
        /// </summary>
        public static string RetailZone {
            get {
                return ResourceManager.GetString("RetailZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Dwelling.
        /// </summary>
        public static string StandardDwelling {
            get {
                return ResourceManager.GetString("StandardDwelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship Hub.
        /// </summary>
        public static string StarshipHub {
            get {
                return ResourceManager.GetString("StarshipHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Unit.
        /// </summary>
        public static string StorageUnit {
            get {
                return ResourceManager.GetString("StorageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substantial Dwelling.
        /// </summary>
        public static string SubstantialDwelling {
            get {
                return ResourceManager.GetString("SubstantialDwelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Tower.
        /// </summary>
        public static string WaterTower {
            get {
                return ResourceManager.GetString("WaterTower", resourceCulture);
            }
        }
    }
}
