//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StarshipResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StarshipResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.StarshipResource", typeof(StarshipResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional notes.
        /// </summary>
        public static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo Slots (Pre-Waypoint).
        /// </summary>
        public static string CargoSlots {
            get {
                return ResourceManager.GetString("CargoSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilized.
        /// </summary>
        public static string CivilizedBy {
            get {
                return ResourceManager.GetString("CivilizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Notes.
        /// </summary>
        public static string DescriptionNotes {
            get {
                return ResourceManager.GetString("DescriptionNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered.
        /// </summary>
        public static string DiscoveredBy {
            get {
                return ResourceManager.GetString("DiscoveredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered Date.
        /// </summary>
        public static string DiscoveredDate {
            get {
                return ResourceManager.GetString("DiscoveredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered Link on Wiki.
        /// </summary>
        public static string DiscoveredLinkOnWiki {
            get {
                return ResourceManager.GetString("DiscoveredLinkOnWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sequence.
        /// </summary>
        public static string DocumentSequence {
            get {
                return ResourceManager.GetString("DocumentSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Cost Evaluation.
        /// </summary>
        public static string FreighterCostEvaluation {
            get {
                return ResourceManager.GetString("FreighterCostEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wings?.
        /// </summary>
        public static string HasWings {
            get {
                return ResourceManager.GetString("HasWings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hull Accessories.
        /// </summary>
        public static string HullAccessories {
            get {
                return ResourceManager.GetString("HullAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Size.
        /// </summary>
        public static string InventorySize {
            get {
                return ResourceManager.GetString("InventorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Notes.
        /// </summary>
        public static string LocationNotes {
            get {
                return ResourceManager.GetString("LocationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Hull Accessories.
        /// </summary>
        public static string MoreHullAccessories {
            get {
                return ResourceManager.GetString("MoreHullAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Color.
        /// </summary>
        public static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Team.
        /// </summary>
        public static string ResearchTeam {
            get {
                return ResourceManager.GetString("ResearchTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Color.
        /// </summary>
        public static string SecondaryColor {
            get {
                return ResourceManager.GetString("SecondaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipSubtype.
        /// </summary>
        public static string ShipSubtype {
            get {
                return ResourceManager.GetString("ShipSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Notes.
        /// </summary>
        public static string SummaryNotes {
            get {
                return ResourceManager.GetString("SummaryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thruster/Engine.
        /// </summary>
        public static string Thruster {
            get {
                return ResourceManager.GetString("Thruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Modules.
        /// </summary>
        public static string UpgradeModules {
            get {
                return ResourceManager.GetString("UpgradeModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Link.
        /// </summary>
        public static string WikiLink {
            get {
                return ResourceManager.GetString("WikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XX (second coord).
        /// </summary>
        public static string XXSecondCoordinate {
            get {
                return ResourceManager.GetString("XXSecondCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YY (first coord).
        /// </summary>
        public static string YYFirstCoordinate {
            get {
                return ResourceManager.GetString("YYFirstCoordinate", resourceCulture);
            }
        }
    }
}
