namespace AGT.GalacticArchives.Core.Enums;

public enum EconomyTypes
{
    Mercantile = 1,
    Trading,
    Shipping,
    Commercial,
    AdvancedMaterials,
    MaterialFusion,
    Alchemical,
    MetalProcessing,
    OreProcessing,
    Research,
    Scientific,
    Experimental,
    Mathematical,
    Mining,
    MineralExtraction,
    OreExtraction,
    Prospecting,
    Manufacturing,
    Industrial,
    Construction,
    MassProduction,
    HighTech,
    Technology,
    NanoConstruction,
    Engineering,
    PowerGeneration,
    EnergySupply,
    FuelGeneration,
    HighVoltage,
    HighElectric,
    None,
    DataUnavailable,
}