//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BiomeSubTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BiomeSubTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.BiomeSubTypeResource", typeof(BiomeSubTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nest.
        /// </summary>
        public static string TheNest {
            get {
                return ResourceManager.GetString("TheNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reliquary.
        /// </summary>
        public static string TheReliquary {
            get {
                return ResourceManager.GetString("TheReliquary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Anomaly.
        /// </summary>
        public static string ToxicAnomaly {
            get {
                return ResourceManager.GetString("ToxicAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Horror.
        /// </summary>
        public static string ToxicHorror {
            get {
                return ResourceManager.GetString("ToxicHorror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultramarine Giant.
        /// </summary>
        public static string UltramarineGiant {
            get {
                return ResourceManager.GetString("UltramarineGiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vermillion Globe.
        /// </summary>
        public static string VermillionGlobe {
            get {
                return ResourceManager.GetString("VermillionGlobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vile Anomaly.
        /// </summary>
        public static string VileAnomaly {
            get {
                return ResourceManager.GetString("VileAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind-Swept.
        /// </summary>
        public static string WindSwept {
            get {
                return ResourceManager.GetString("WindSwept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine Dark.
        /// </summary>
        public static string WineDark {
            get {
                return ResourceManager.GetString("WineDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worm-Ridden.
        /// </summary>
        public static string WormRidden {
            get {
                return ResourceManager.GetString("WormRidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xeno-Colony.
        /// </summary>
        public static string XenoColony {
            get {
                return ResourceManager.GetString("XenoColony", resourceCulture);
            }
        }
    }
}
