//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization.Planet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EdibleRawMaterialTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EdibleRawMaterialTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.Planet.EdibleRawMaterialTypeResource", typeof(EdibleRawMaterialTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cactus Nectar.
        /// </summary>
        public static string CactusNectar {
            get {
                return ResourceManager.GetString("CactusNectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab &apos;Apple&apos;.
        /// </summary>
        public static string CrabApple {
            get {
                return ResourceManager.GetString("CrabApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature Egg.
        /// </summary>
        public static string CreatureEgg {
            get {
                return ResourceManager.GetString("CreatureEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplo Chunks.
        /// </summary>
        public static string DiploChunks {
            get {
                return ResourceManager.GetString("DiploChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feline Liver.
        /// </summary>
        public static string FelineLiver {
            get {
                return ResourceManager.GetString("FelineLiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiendish Roe.
        /// </summary>
        public static string FiendishRoe {
            get {
                return ResourceManager.GetString("FiendishRoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Milk.
        /// </summary>
        public static string FreshMilk {
            get {
                return ResourceManager.GetString("FreshMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giant Egg.
        /// </summary>
        public static string GiantEgg {
            get {
                return ResourceManager.GetString("GiantEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Grains.
        /// </summary>
        public static string GlassGrains {
            get {
                return ResourceManager.GetString("GlassGrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heptaploid Wheat.
        /// </summary>
        public static string HeptaploidWheat {
            get {
                return ResourceManager.GetString("HeptaploidWheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelp Rice.
        /// </summary>
        public static string KelpRice {
            get {
                return ResourceManager.GetString("KelpRice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg Meat.
        /// </summary>
        public static string LegMeat {
            get {
                return ResourceManager.GetString("LegMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leopard-Fruit.
        /// </summary>
        public static string LeopardFruit {
            get {
                return ResourceManager.GetString("LeopardFruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marrow Flesh.
        /// </summary>
        public static string MarrowFlesh {
            get {
                return ResourceManager.GetString("MarrowFlesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat Flakes.
        /// </summary>
        public static string MeatFlakes {
            get {
                return ResourceManager.GetString("MeatFlakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaty Chunks.
        /// </summary>
        public static string MeatyChunks {
            get {
                return ResourceManager.GetString("MeatyChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaty Wings.
        /// </summary>
        public static string MeatyWings {
            get {
                return ResourceManager.GetString("MeatyWings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Toxic Mushroom.
        /// </summary>
        public static string NonToxicMushroom {
            get {
                return ResourceManager.GetString("NonToxicMushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offal Sac.
        /// </summary>
        public static string OffalSac {
            get {
                return ResourceManager.GetString("OffalSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulpy Roots.
        /// </summary>
        public static string PulpyRoots {
            get {
                return ResourceManager.GetString("PulpyRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Steak.
        /// </summary>
        public static string RawSteak {
            get {
                return ResourceManager.GetString("RawSteak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regis Grease.
        /// </summary>
        public static string RegisGrease {
            get {
                return ResourceManager.GetString("RegisGrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salty Fingers.
        /// </summary>
        public static string SaltyFingers {
            get {
                return ResourceManager.GetString("SaltyFingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaly Meat.
        /// </summary>
        public static string ScalyMeat {
            get {
                return ResourceManager.GetString("ScalyMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sievert Beans.
        /// </summary>
        public static string SievertBeans {
            get {
                return ResourceManager.GetString("SievertBeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silicon Egg.
        /// </summary>
        public static string SiliconEgg {
            get {
                return ResourceManager.GetString("SiliconEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steamed Vegetables.
        /// </summary>
        public static string SteamedVegetables {
            get {
                return ResourceManager.GetString("SteamedVegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky &apos;Honey&apos;.
        /// </summary>
        public static string StickyHoney {
            get {
                return ResourceManager.GetString("StickyHoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strider Sausage.
        /// </summary>
        public static string StriderSausage {
            get {
                return ResourceManager.GetString("StriderSausage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall Eggs.
        /// </summary>
        public static string TallEggs {
            get {
                return ResourceManager.GetString("TallEggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Proto-Milk.
        /// </summary>
        public static string WarmProtoMilk {
            get {
                return ResourceManager.GetString("WarmProtoMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Milk.
        /// </summary>
        public static string WildMilk {
            get {
                return ResourceManager.GetString("WildMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Yeast.
        /// </summary>
        public static string WildYeast {
            get {
                return ResourceManager.GetString("WildYeast", resourceCulture);
            }
        }
    }
}
