//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaunaDietResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaunaDietResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.Planet.FaunaDietResource", typeof(FaunaDietResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorbed Nutrients.
        /// </summary>
        public static string AbsorbedNutrients {
            get {
                return ResourceManager.GetString("AbsorbedNutrients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algal Particulates.
        /// </summary>
        public static string AlgalParticulates {
            get {
                return ResourceManager.GetString("AlgalParticulates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood-Drinker.
        /// </summary>
        public static string BloodDrinker {
            get {
                return ResourceManager.GetString("BloodDrinker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiled Meat.
        /// </summary>
        public static string BoiledMeat {
            get {
                return ResourceManager.GetString("BoiledMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brain Matter.
        /// </summary>
        public static string BrainMatter {
            get {
                return ResourceManager.GetString("BrainMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cave Marrow.
        /// </summary>
        public static string CaveMarrow {
            get {
                return ResourceManager.GetString("CaveMarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coagulated Blood.
        /// </summary>
        public static string CoagulatedBlood {
            get {
                return ResourceManager.GetString("CoagulatedBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collects Seeds.
        /// </summary>
        public static string CollectsSeeds {
            get {
                return ResourceManager.GetString("CollectsSeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condensed Carbon.
        /// </summary>
        public static string CondensedCarbon {
            get {
                return ResourceManager.GetString("CondensedCarbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmic Rays.
        /// </summary>
        public static string CosmicRays {
            get {
                return ResourceManager.GetString("CosmicRays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crunches Bones.
        /// </summary>
        public static string CrunchesBones {
            get {
                return ResourceManager.GetString("CrunchesBones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decaying Atoms.
        /// </summary>
        public static string DecayingAtoms {
            get {
                return ResourceManager.GetString("DecayingAtoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decaying Plant Life.
        /// </summary>
        public static string DecayingPlantLife {
            get {
                return ResourceManager.GetString("DecayingPlantLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deepwater Algae.
        /// </summary>
        public static string DeepwaterAlgae {
            get {
                return ResourceManager.GetString("DeepwaterAlgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deepwater Spores.
        /// </summary>
        public static string DeepwaterSpores {
            get {
                return ResourceManager.GetString("DeepwaterSpores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digs For Tubers.
        /// </summary>
        public static string DigsForTubers {
            get {
                return ResourceManager.GetString("DigsForTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di-Hydrogen Crystals.
        /// </summary>
        public static string DiHydrogenCrystals {
            get {
                return ResourceManager.GetString("DiHydrogenCrystals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drifting Plants.
        /// </summary>
        public static string DriftingPlants {
            get {
                return ResourceManager.GetString("DriftingPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts Bone Marrow.
        /// </summary>
        public static string ExtractsBoneMarrow {
            get {
                return ResourceManager.GetString("ExtractsBoneMarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetid Meat.
        /// </summary>
        public static string FetidMeat {
            get {
                return ResourceManager.GetString("FetidMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flesh Chunks.
        /// </summary>
        public static string FleshChunks {
            get {
                return ResourceManager.GetString("FleshChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flesh-Eater.
        /// </summary>
        public static string FleshEater {
            get {
                return ResourceManager.GetString("FleshEater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foraged Leftovers.
        /// </summary>
        public static string ForagedLeftovers {
            get {
                return ResourceManager.GetString("ForagedLeftovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foraged Nuts.
        /// </summary>
        public static string ForagedNuts {
            get {
                return ResourceManager.GetString("ForagedNuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Leaves.
        /// </summary>
        public static string FreshLeaves {
            get {
                return ResourceManager.GetString("FreshLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Meat.
        /// </summary>
        public static string FreshMeat {
            get {
                return ResourceManager.GetString("FreshMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen Meat.
        /// </summary>
        public static string FrozenMeat {
            get {
                return ResourceManager.GetString("FrozenMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fungal Cluster.
        /// </summary>
        public static string FungalCluster {
            get {
                return ResourceManager.GetString("FungalCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma Weed.
        /// </summary>
        public static string GammaWeed {
            get {
                return ResourceManager.GetString("GammaWeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitino Balls.
        /// </summary>
        public static string GravitinoBalls {
            get {
                return ResourceManager.GetString("GravitinoBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grazing Creature.
        /// </summary>
        public static string GrazingCreature {
            get {
                return ResourceManager.GetString("GrazingCreature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Meat.
        /// </summary>
        public static string GroundMeat {
            get {
                return ResourceManager.GetString("GroundMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High In Calcium.
        /// </summary>
        public static string HighInCalcium {
            get {
                return ResourceManager.GetString("HighInCalcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunts Squid.
        /// </summary>
        public static string HuntsSquid {
            get {
                return ResourceManager.GetString("HuntsSquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrothermal Minerals.
        /// </summary>
        public static string HydrothermalMinerals {
            get {
                return ResourceManager.GetString("HydrothermalMinerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypnotises Prey.
        /// </summary>
        public static string HypnotisesPrey {
            get {
                return ResourceManager.GetString("HypnotisesPrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insect-Eater.
        /// </summary>
        public static string InsectEater {
            get {
                return ResourceManager.GetString("InsectEater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insects And Grubs.
        /// </summary>
        public static string InsectsAndGrubs {
            get {
                return ResourceManager.GetString("InsectsAndGrubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelp Sacs.
        /// </summary>
        public static string KelpSacs {
            get {
                return ResourceManager.GetString("KelpSacs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Mammals.
        /// </summary>
        public static string LargeMammals {
            get {
                return ResourceManager.GetString("LargeMammals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidised Organs.
        /// </summary>
        public static string LiquidisedOrgans {
            get {
                return ResourceManager.GetString("LiquidisedOrgans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Sponges.
        /// </summary>
        public static string LivingSponges {
            get {
                return ResourceManager.GetString("LivingSponges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Detritus.
        /// </summary>
        public static string MarineDetritus {
            get {
                return ResourceManager.GetString("MarineDetritus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Snow.
        /// </summary>
        public static string MarineSnow {
            get {
                return ResourceManager.GetString("MarineSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat Chunks.
        /// </summary>
        public static string MeatChunks {
            get {
                return ResourceManager.GetString("MeatChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat-Eater.
        /// </summary>
        public static string MeatEater {
            get {
                return ResourceManager.GetString("MeatEater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mordite Root.
        /// </summary>
        public static string MorditeRoot {
            get {
                return ResourceManager.GetString("MorditeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly Rocks.
        /// </summary>
        public static string MostlyRocks {
            get {
                return ResourceManager.GetString("MostlyRocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nibbles At Moss.
        /// </summary>
        public static string NibblesAtMoss {
            get {
                return ResourceManager.GetString("NibblesAtMoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nibbles At Shoots.
        /// </summary>
        public static string NibblesAtShoots {
            get {
                return ResourceManager.GetString("NibblesAtShoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nipnip Buds.
        /// </summary>
        public static string NipnipBuds {
            get {
                return ResourceManager.GetString("NipnipBuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrous Oxide.
        /// </summary>
        public static string NitrousOxide {
            get {
                return ResourceManager.GetString("NitrousOxide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritious Water Weeds.
        /// </summary>
        public static string NutritiousWaterWeeds {
            get {
                return ResourceManager.GetString("NutritiousWaterWeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Bones.
        /// </summary>
        public static string OldBones {
            get {
                return ResourceManager.GetString("OldBones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Carnivores.
        /// </summary>
        public static string OtherCarnivores {
            get {
                return ResourceManager.GetString("OtherCarnivores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Fish.
        /// </summary>
        public static string OtherFish {
            get {
                return ResourceManager.GetString("OtherFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxide Elements.
        /// </summary>
        public static string OxideElements {
            get {
                return ResourceManager.GetString("OxideElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially Digested Meat.
        /// </summary>
        public static string PartiallyDigestedMeat {
            get {
                return ResourceManager.GetString("PartiallyDigestedMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Roots.
        /// </summary>
        public static string PlantRoots {
            get {
                return ResourceManager.GetString("PlantRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserved Meat.
        /// </summary>
        public static string PreservedMeat {
            get {
                return ResourceManager.GetString("PreservedMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes Dirt.
        /// </summary>
        public static string ProcessesDirt {
            get {
                return ResourceManager.GetString("ProcessesDirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putrefied Meat.
        /// </summary>
        public static string PutrefiedMeat {
            get {
                return ResourceManager.GetString("PutrefiedMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radioactive Meat.
        /// </summary>
        public static string RadioactiveMeat {
            get {
                return ResourceManager.GetString("RadioactiveMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Meat.
        /// </summary>
        public static string RawMeat {
            get {
                return ResourceManager.GetString("RawMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Hearts.
        /// </summary>
        public static string RemovedHearts {
            get {
                return ResourceManager.GetString("RemovedHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotten Meat.
        /// </summary>
        public static string RottenMeat {
            get {
                return ResourceManager.GetString("RottenMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotten Wood.
        /// </summary>
        public static string RottenWood {
            get {
                return ResourceManager.GetString("RottenWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotting Fruit.
        /// </summary>
        public static string RottingFruit {
            get {
                return ResourceManager.GetString("RottingFruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scavenged Remains.
        /// </summary>
        public static string ScavengedRemains {
            get {
                return ResourceManager.GetString("ScavengedRemains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scavenged Scraps.
        /// </summary>
        public static string ScavengedScraps {
            get {
                return ResourceManager.GetString("ScavengedScraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Animals.
        /// </summary>
        public static string SmallAnimals {
            get {
                return ResourceManager.GetString("SmallAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Crustaceans.
        /// </summary>
        public static string SmallCrustaceans {
            get {
                return ResourceManager.GetString("SmallCrustaceans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Fruit.
        /// </summary>
        public static string SmallFruit {
            get {
                return ResourceManager.GetString("SmallFruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Trees.
        /// </summary>
        public static string SmallTrees {
            get {
                return ResourceManager.GetString("SmallTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Vine.
        /// </summary>
        public static string SolarVine {
            get {
                return ResourceManager.GetString("SolarVine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Bramble.
        /// </summary>
        public static string StarBramble {
            get {
                return ResourceManager.GetString("StarBramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steals From Others.
        /// </summary>
        public static string StealsFromOthers {
            get {
                return ResourceManager.GetString("StealsFromOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stinging Leaves.
        /// </summary>
        public static string StingingLeaves {
            get {
                return ResourceManager.GetString("StingingLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall Grasses.
        /// </summary>
        public static string TallGrasses {
            get {
                return ResourceManager.GetString("TallGrasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Meat.
        /// </summary>
        public static string ToxicMeat {
            get {
                return ResourceManager.GetString("ToxicMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venom Urchins.
        /// </summary>
        public static string VenomUrchins {
            get {
                return ResourceManager.GetString("VenomUrchins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vented Minerals.
        /// </summary>
        public static string VentedMinerals {
            get {
                return ResourceManager.GetString("VentedMinerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Filtration.
        /// </summary>
        public static string WaterFiltration {
            get {
                return ResourceManager.GetString("WaterFiltration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Vines.
        /// </summary>
        public static string WaterVines {
            get {
                return ResourceManager.GetString("WaterVines", resourceCulture);
            }
        }
    }
}
