//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaunaBaitTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaunaBaitTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.FaunaBaitTypeResource", typeof(FaunaBaitTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloody Organ.
        /// </summary>
        public static string BloodyOrgan {
            get {
                return ResourceManager.GetString("BloodyOrgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature Pellets.
        /// </summary>
        public static string CreaturePellets {
            get {
                return ResourceManager.GetString("CreaturePellets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enzyme Fluid.
        /// </summary>
        public static string EnzymeFluid {
            get {
                return ResourceManager.GetString("EnzymeFluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermented Fruit.
        /// </summary>
        public static string FermentedFruit {
            get {
                return ResourceManager.GetString("FermentedFruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Meat.
        /// </summary>
        public static string GroundMeat {
            get {
                return ResourceManager.GetString("GroundMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pheromone Sac.
        /// </summary>
        public static string PheromoneSac {
            get {
                return ResourceManager.GetString("PheromoneSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scented Herbs.
        /// </summary>
        public static string ScentedHerbs {
            get {
                return ResourceManager.GetString("ScentedHerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweetened Compost.
        /// </summary>
        public static string SweetenedCompost {
            get {
                return ResourceManager.GetString("SweetenedCompost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthetic Worms.
        /// </summary>
        public static string SyntheticWorms {
            get {
                return ResourceManager.GetString("SyntheticWorms", resourceCulture);
            }
        }
    }
}
