//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaunaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaunaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.Planet.FaunaResource", typeof(FaunaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone Nuggets.
        /// </summary>
        public static string BoneNuggets {
            get {
                return ResourceManager.GetString("BoneNuggets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceaseless Burrower.
        /// </summary>
        public static string CeaselessBurrower {
            get {
                return ResourceManager.GetString("CeaselessBurrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chewy Wires.
        /// </summary>
        public static string ChewyWires {
            get {
                return ResourceManager.GetString("ChewyWires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colossal Being.
        /// </summary>
        public static string ColossalBeing {
            get {
                return ResourceManager.GetString("ColossalBeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab &apos;Apple&apos;.
        /// </summary>
        public static string CrabApple {
            get {
                return ResourceManager.GetString("CrabApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craw Milk.
        /// </summary>
        public static string CrawMilk {
            get {
                return ResourceManager.GetString("CrawMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature Egg.
        /// </summary>
        public static string CreatureEgg {
            get {
                return ResourceManager.GetString("CreatureEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirty Meat.
        /// </summary>
        public static string DirtyMeat {
            get {
                return ResourceManager.GetString("DirtyMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiendish Roe.
        /// </summary>
        public static string FiendishRoe {
            get {
                return ResourceManager.GetString("FiendishRoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foraged Mushrooms.
        /// </summary>
        public static string ForagedMushrooms {
            get {
                return ResourceManager.GetString("ForagedMushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Milk.
        /// </summary>
        public static string FreshMilk {
            get {
                return ResourceManager.GetString("FreshMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giant Egg.
        /// </summary>
        public static string GiantEgg {
            get {
                return ResourceManager.GetString("GiantEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giant Parasite.
        /// </summary>
        public static string GiantParasite {
            get {
                return ResourceManager.GetString("GiantParasite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leopard-Fruit.
        /// </summary>
        public static string LeopardFruit {
            get {
                return ResourceManager.GetString("LeopardFruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nourishing Slime.
        /// </summary>
        public static string NourishingSlime {
            get {
                return ResourceManager.GetString("NourishingSlime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planetary Maggot.
        /// </summary>
        public static string PlanetaryMaggot {
            get {
                return ResourceManager.GetString("PlanetaryMaggot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regis Grease.
        /// </summary>
        public static string RegisGrease {
            get {
                return ResourceManager.GetString("RegisGrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Mouth.
        /// </summary>
        public static string RoundMouth {
            get {
                return ResourceManager.GetString("RoundMouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky &apos;Honey&apos;.
        /// </summary>
        public static string StickyHoney {
            get {
                return ResourceManager.GetString("StickyHoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall Eggs.
        /// </summary>
        public static string TallEggs {
            get {
                return ResourceManager.GetString("TallEggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Consumer.
        /// </summary>
        public static string TheConsumer {
            get {
                return ResourceManager.GetString("TheConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstoppable Nematode.
        /// </summary>
        public static string UnstoppableNematode {
            get {
                return ResourceManager.GetString("UnstoppableNematode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Proto-Milk.
        /// </summary>
        public static string WarmProtoMilk {
            get {
                return ResourceManager.GetString("WarmProtoMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Milk.
        /// </summary>
        public static string WildMilk {
            get {
                return ResourceManager.GetString("WildMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worm Lord.
        /// </summary>
        public static string WormLord {
            get {
                return ResourceManager.GetString("WormLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wraith-Like.
        /// </summary>
        public static string WraithLike {
            get {
                return ResourceManager.GetString("WraithLike", resourceCulture);
            }
        }
    }
}
