//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LandArchetypesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandArchetypesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.Planet.LandArchetypesResource", typeof(LandArchetypesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chasms (Mountains).
        /// </summary>
        public static string ChasmsMountains {
            get {
                return ResourceManager.GetString("ChasmsMountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honeycomb.
        /// </summary>
        public static string Honeycomb {
            get {
                return ResourceManager.GetString("Honeycomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesa.
        /// </summary>
        public static string Mesa {
            get {
                return ResourceManager.GetString("Mesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monoliths.
        /// </summary>
        public static string Monoliths {
            get {
                return ResourceManager.GetString("Monoliths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountains.
        /// </summary>
        public static string Mountains {
            get {
                return ResourceManager.GetString("Mountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaks (Mountains).
        /// </summary>
        public static string PeaksMountains {
            get {
                return ResourceManager.GetString("PeaksMountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Pillars.
        /// </summary>
        public static string RockPillars {
            get {
                return ResourceManager.GetString("RockPillars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Hills (Mountains).
        /// </summary>
        public static string RollingHillsMountains {
            get {
                return ResourceManager.GetString("RollingHillsMountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Mountains (Mountains).
        /// </summary>
        public static string RollingMountainsMountains {
            get {
                return ResourceManager.GetString("RollingMountainsMountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rugged Mountains (Mountains).
        /// </summary>
        public static string RuggedMountainsMountains {
            get {
                return ResourceManager.GetString("RuggedMountainsMountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoneroot.
        /// </summary>
        public static string Stoneroot {
            get {
                return ResourceManager.GetString("Stoneroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall Mountains (Mountains).
        /// </summary>
        public static string TallMountainsMountains {
            get {
                return ResourceManager.GetString("TallMountainsMountains", resourceCulture);
            }
        }
    }
}
