//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LandResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.Planet.LandResource", typeof(LandResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpine mountainous.
        /// </summary>
        public static string AlpineMountainous {
            get {
                return ResourceManager.GetString("AlpineMountainous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat plains.
        /// </summary>
        public static string FlatPlains {
            get {
                return ResourceManager.GetString("FlatPlains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat plains/hilly.
        /// </summary>
        public static string FlatPlainsHilly {
            get {
                return ResourceManager.GetString("FlatPlainsHilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Plains/Ocean.
        /// </summary>
        public static string FlatPlainsOcean {
            get {
                return ResourceManager.GetString("FlatPlainsOcean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat plains/rocky.
        /// </summary>
        public static string FlatPlainsRocky {
            get {
                return ResourceManager.GetString("FlatPlainsRocky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hilly.
        /// </summary>
        public static string Hilly {
            get {
                return ResourceManager.GetString("Hilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hilly/mountainous.
        /// </summary>
        public static string HillyMountainous {
            get {
                return ResourceManager.GetString("HillyMountainous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mountainous.
        /// </summary>
        public static string Mountainous {
            get {
                return ResourceManager.GetString("Mountainous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rocky/hilly.
        /// </summary>
        public static string RockyHilly {
            get {
                return ResourceManager.GetString("RockyHilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rough hills.
        /// </summary>
        public static string RoughHills {
            get {
                return ResourceManager.GetString("RoughHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small islands/ocean.
        /// </summary>
        public static string SmallIslandsOcean {
            get {
                return ResourceManager.GetString("SmallIslandsOcean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waterworld.
        /// </summary>
        public static string Waterworld {
            get {
                return ResourceManager.GetString("Waterworld", resourceCulture);
            }
        }
    }
}
