//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanetAtmosphereColorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanetAtmosphereColorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.PlanetAtmosphereColorResource", typeof(PlanetAtmosphereColorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue green.
        /// </summary>
        public static string BlueGreen {
            get {
                return ResourceManager.GetString("BlueGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue grey.
        /// </summary>
        public static string Bluegrey {
            get {
                return ResourceManager.GetString("Bluegrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue violet.
        /// </summary>
        public static string Blueviolet {
            get {
                return ResourceManager.GetString("Blueviolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnation pink.
        /// </summary>
        public static string CarnationPink {
            get {
                return ResourceManager.GetString("CarnationPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome blue.
        /// </summary>
        public static string MonochromeBlue {
            get {
                return ResourceManager.GetString("MonochromeBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome green.
        /// </summary>
        public static string MonochromeGreen {
            get {
                return ResourceManager.GetString("MonochromeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome orange.
        /// </summary>
        public static string MonochromeOrange {
            get {
                return ResourceManager.GetString("MonochromeOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome red.
        /// </summary>
        public static string MonochromeRed {
            get {
                return ResourceManager.GetString("MonochromeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome yellow.
        /// </summary>
        public static string MonochromeYellow {
            get {
                return ResourceManager.GetString("MonochromeYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red orange.
        /// </summary>
        public static string RedOrange {
            get {
                return ResourceManager.GetString("RedOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red violet.
        /// </summary>
        public static string RedViolet {
            get {
                return ResourceManager.GetString("RedViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet red.
        /// </summary>
        public static string VioletRed {
            get {
                return ResourceManager.GetString("VioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow green.
        /// </summary>
        public static string YellowGreen {
            get {
                return ResourceManager.GetString("YellowGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow orange.
        /// </summary>
        public static string YellowOrange {
            get {
                return ResourceManager.GetString("YellowOrange", resourceCulture);
            }
        }
    }
}
