//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization.Planet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanetResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanetResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.Planet.PlanetResource", typeof(PlanetResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Notes.
        /// </summary>
        public static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor and admin notes on data quality.
        /// </summary>
        public static string AdminNotes {
            get {
                return ResourceManager.GetString("AdminNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of Planet (Billions of years).
        /// </summary>
        public static string AgeOfPlanetInBillionsOfYears {
            get {
                return ResourceManager.GetString("AgeOfPlanetInBillionsOfYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archetype of Land.
        /// </summary>
        public static string ArchetypeOfLand {
            get {
                return ResourceManager.GetString("ArchetypeOfLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignedRawIngredient.
        /// </summary>
        public static string AssignedRawIngredient {
            get {
                return ResourceManager.GetString("AssignedRawIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere Daytime Color.
        /// </summary>
        public static string AtmosphereDaytimeColor {
            get {
                return ResourceManager.GetString("AtmosphereDaytimeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere Gas 1.
        /// </summary>
        public static string AtmosphereGas1 {
            get {
                return ResourceManager.GetString("AtmosphereGas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere Gas 2.
        /// </summary>
        public static string AtmosphereGas2 {
            get {
                return ResourceManager.GetString("AtmosphereGas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atm. Gas 1 %.
        /// </summary>
        public static string AtmosphereGasPercentage1 {
            get {
                return ResourceManager.GetString("AtmosphereGasPercentage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atm. Gas 2 %.
        /// </summary>
        public static string AtmosphereGasPercentage2 {
            get {
                return ResourceManager.GetString("AtmosphereGasPercentage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere resource.
        /// </summary>
        public static string AtmosphereResource {
            get {
                return ResourceManager.GetString("AtmosphereResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biome Description.
        /// </summary>
        public static string BiomeDescription {
            get {
                return ResourceManager.GetString("BiomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource 4 (Automatic based on biome).
        /// </summary>
        public static string BiomeResource {
            get {
                return ResourceManager.GetString("BiomeResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biome Type.
        /// </summary>
        public static string BiomeType {
            get {
                return ResourceManager.GetString("BiomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        public static string Civilization {
            get {
                return ResourceManager.GetString("Civilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Quality Check.
        /// </summary>
        public static string DataQualityCheck {
            get {
                return ResourceManager.GetString("DataQualityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Radiation.
        /// </summary>
        public static string DayRadiation {
            get {
                return ResourceManager.GetString("DayRadiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Storm Radiation.
        /// </summary>
        public static string DayStormRadiation {
            get {
                return ResourceManager.GetString("DayStormRadiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Storm Temp (celsius).
        /// </summary>
        public static string DayStormTemp {
            get {
                return ResourceManager.GetString("DayStormTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Storm Toxic.
        /// </summary>
        public static string DayStormToxic {
            get {
                return ResourceManager.GetString("DayStormToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Temp (celsius).
        /// </summary>
        public static string DayTemp {
            get {
                return ResourceManager.GetString("DayTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Toxic.
        /// </summary>
        public static string DayToxic {
            get {
                return ResourceManager.GetString("DayToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered Link on Wiki.
        /// </summary>
        public static string DiscoveredLinkOnWiki {
            get {
                return ResourceManager.GetString("DiscoveredLinkOnWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discoverer Gamertag.
        /// </summary>
        public static string DiscovererGamertag {
            get {
                return ResourceManager.GetString("DiscovererGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Date.
        /// </summary>
        public static string DiscoveryDate {
            get {
                return ResourceManager.GetString("DiscoveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Platform.
        /// </summary>
        public static string DiscoveryPlatform {
            get {
                return ResourceManager.GetString("DiscoveryPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Link 1.
        /// </summary>
        public static string ExternalLink1 {
            get {
                return ResourceManager.GetString("ExternalLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Link 2.
        /// </summary>
        public static string ExternalLink2 {
            get {
                return ResourceManager.GetString("ExternalLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras A.
        /// </summary>
        public static string ExtrasA {
            get {
                return ResourceManager.GetString("ExtrasA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras B.
        /// </summary>
        public static string ExtrasB {
            get {
                return ResourceManager.GetString("ExtrasB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras C.
        /// </summary>
        public static string ExtrasC {
            get {
                return ResourceManager.GetString("ExtrasC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Weather (Excludes Mega Exotic).
        /// </summary>
        public static string ExtremeWeatherExcludingMegaExotic {
            get {
                return ResourceManager.GetString("ExtremeWeatherExcludingMegaExotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Weather for Mega-Exotic/ Waterworld Manual Entry.
        /// </summary>
        public static string ExtremeWeatherInludingMegaExotic {
            get {
                return ResourceManager.GetString("ExtremeWeatherInludingMegaExotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fauna.
        /// </summary>
        public static string FaunaCategory {
            get {
                return ResourceManager.GetString("FaunaCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version Number for Page.
        /// </summary>
        public static string GameVersionNumberForPage {
            get {
                return ResourceManager.GetString("GameVersionNumberForPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandworms?.
        /// </summary>
        public static string HasSandworms {
            get {
                return ResourceManager.GetString("HasSandworms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Planet Discover Credit Before Reset.
        /// </summary>
        public static string HistoricalPlanetDiscoverCreditBeforeReset {
            get {
                return ResourceManager.GetString("HistoricalPlanetDiscoverCreditBeforeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Planet Name (Last Known Era).
        /// </summary>
        public static string HistoricalPlanetNameLastKnownEra {
            get {
                return ResourceManager.GetString("HistoricalPlanetNameLastKnownEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Planet Name (Platform).
        /// </summary>
        public static string HistoricalPlanetNamePlatform {
            get {
                return ResourceManager.GetString("HistoricalPlanetNamePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Planet Name (Reset).
        /// </summary>
        public static string HistoricalPlanetNameReset {
            get {
                return ResourceManager.GetString("HistoricalPlanetNameReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infected?
        ///ORIGINS+.
        /// </summary>
        public static string IsInfected {
            get {
                return ResourceManager.GetString("IsInfected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PC Discoverers GamerTag Name.
        /// </summary>
        public static string LegacyPCDiscoverersGamerTagName {
            get {
                return ResourceManager.GetString("LegacyPCDiscoverersGamerTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PC Discovery Date.
        /// </summary>
        public static string LegacyPCDiscoveryDate {
            get {
                return ResourceManager.GetString("LegacyPCDiscoveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PC Discovery Era.
        /// </summary>
        public static string LegacyPCDiscoveryEra {
            get {
                return ResourceManager.GetString("LegacyPCDiscoveryEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PC planet name.
        /// </summary>
        public static string LegacyPCPlanetName {
            get {
                return ResourceManager.GetString("LegacyPCPlanetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PS Discoverers GamerTag Name.
        /// </summary>
        public static string LegacyPSDiscoverersGamerTagName {
            get {
                return ResourceManager.GetString("LegacyPSDiscoverersGamerTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PS Discovery Date.
        /// </summary>
        public static string LegacyPSDiscoveryDate {
            get {
                return ResourceManager.GetString("LegacyPSDiscoveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PS Discovery Era.
        /// </summary>
        public static string LegacyPSDiscoveryEra {
            get {
                return ResourceManager.GetString("LegacyPSDiscoveryEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PS planet name.
        /// </summary>
        public static string LegacyPSPlanetName {
            get {
                return ResourceManager.GetString("LegacyPSPlanetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Wiki Link Other.
        /// </summary>
        public static string LegacyWikiLinkOther {
            get {
                return ResourceManager.GetString("LegacyWikiLinkOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Wiki Link PC.
        /// </summary>
        public static string LegacyWikiLinkPC {
            get {
                return ResourceManager.GetString("LegacyWikiLinkPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Wiki Link PS.
        /// </summary>
        public static string LegacyWikiLinkPS {
            get {
                return ResourceManager.GetString("LegacyWikiLinkPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Wiki Link Xbox.
        /// </summary>
        public static string LegacyWikiLinkXbox {
            get {
                return ResourceManager.GetString("LegacyWikiLinkXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY Xbox Discoverers GamerTag Name.
        /// </summary>
        public static string LegacyXboxDiscoverersGamerTagName {
            get {
                return ResourceManager.GetString("LegacyXboxDiscoverersGamerTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY Xbox Discovery Date.
        /// </summary>
        public static string LegacyXboxDiscoveryDate {
            get {
                return ResourceManager.GetString("LegacyXboxDiscoveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY Xbox Discovery Era.
        /// </summary>
        public static string LegacyXboxDiscoveryEra {
            get {
                return ResourceManager.GetString("LegacyXboxDiscoveryEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY Xbox planet name.
        /// </summary>
        public static string LegacyXboxPlanetName {
            get {
                return ResourceManager.GetString("LegacyXboxPlanetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Storm Temp (celsius).
        /// </summary>
        public static string NightStormTemp {
            get {
                return ResourceManager.GetString("NightStormTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Temp (celsius).
        /// </summary>
        public static string NightTemp {
            get {
                return ResourceManager.GetString("NightTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Fauna.
        /// </summary>
        public static string NumberOfFauna {
            get {
                return ResourceManager.GetString("NumberOfFauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Planet Name (Before renaming).
        /// </summary>
        public static string OriginalPlanetName {
            get {
                return ResourceManager.GetString("OriginalPlanetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Notes.
        /// </summary>
        public static string OtherNotes {
            get {
                return ResourceManager.GetString("OtherNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Glyphs.
        /// </summary>
        public static string PlanetGlyphs {
            get {
                return ResourceManager.GetString("PlanetGlyphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet ID in system.
        /// </summary>
        public static string PlanetIdInSystem {
            get {
                return ResourceManager.GetString("PlanetIdInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet- moon match.
        /// </summary>
        public static string PlanetMoonMatch {
            get {
                return ResourceManager.GetString("PlanetMoonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Name (All platforms).
        /// </summary>
        public static string PlanetNameAllPlatforms {
            get {
                return ResourceManager.GetString("PlanetNameAllPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet or Moon?.
        /// </summary>
        public static string PlanetOrMoon {
            get {
                return ResourceManager.GetString("PlanetOrMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet/moon Added in Origins?.
        /// </summary>
        public static string PlanetOrMoonAddedInOrigins {
            get {
                return ResourceManager.GetString("PlanetOrMoonAddedInOrigins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Repository.
        /// </summary>
        public static string PortalRepository {
            get {
                return ResourceManager.GetString("PortalRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Core Element.
        /// </summary>
        public static string PrimaryCoreElement {
            get {
                return ResourceManager.GetString("PrimaryCoreElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Resource 1.
        /// </summary>
        public static string PrimaryResource1 {
            get {
                return ResourceManager.GetString("PrimaryResource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Resource 2.
        /// </summary>
        public static string PrimaryResource2 {
            get {
                return ResourceManager.GetString("PrimaryResource2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Resource 3.
        /// </summary>
        public static string PrimaryResource3 {
            get {
                return ResourceManager.GetString("PrimaryResource3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Ingredients.
        /// </summary>
        public static string RawIngredients {
            get {
                return ResourceManager.GetString("RawIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Team.
        /// </summary>
        public static string ResearchTeam {
            get {
                return ResourceManager.GetString("ResearchTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings or Giant?.
        /// </summary>
        public static string RingsOrGiant {
            get {
                return ResourceManager.GetString("RingsOrGiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special A.
        /// </summary>
        public static string SpecialA {
            get {
                return ResourceManager.GetString("SpecialA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Info.
        /// </summary>
        public static string SummaryInfo {
            get {
                return ResourceManager.GetString("SummaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Date.
        /// </summary>
        public static string SurveyDate {
            get {
                return ResourceManager.GetString("SurveyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor Gamertag.
        /// </summary>
        public static string SurveyorGamertag {
            get {
                return ResourceManager.GetString("SurveyorGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Release Era.
        /// </summary>
        public static string SurveyReleaseEra {
            get {
                return ResourceManager.GetString("SurveyReleaseEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Land.
        /// </summary>
        public static string TypeOfLand {
            get {
                return ResourceManager.GetString("TypeOfLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground Day Radiation.
        /// </summary>
        public static string UndergroundDayRadiation {
            get {
                return ResourceManager.GetString("UndergroundDayRadiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground Day Storm Radiation.
        /// </summary>
        public static string UndergroundDayStormRadiation {
            get {
                return ResourceManager.GetString("UndergroundDayStormRadiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground Day Storm Temp (celsius).
        /// </summary>
        public static string UndergroundDayStormTemp {
            get {
                return ResourceManager.GetString("UndergroundDayStormTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground Day Storm Toxic.
        /// </summary>
        public static string UndergroundDayStormToxic {
            get {
                return ResourceManager.GetString("UndergroundDayStormToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground Day Temp (celsius).
        /// </summary>
        public static string UndergroundDayTemp {
            get {
                return ResourceManager.GetString("UndergroundDayTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground Day Toxic.
        /// </summary>
        public static string UndergroundDayToxic {
            get {
                return ResourceManager.GetString("UndergroundDayToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground Night Storm Temp (celsius).
        /// </summary>
        public static string UndergroundNightStormTemp {
            get {
                return ResourceManager.GetString("UndergroundNightStormTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground Night Temp (celsius).
        /// </summary>
        public static string UndergroundNightTemp {
            get {
                return ResourceManager.GetString("UndergroundNightTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwater Day Radiation.
        /// </summary>
        public static string UnderwaterDayRadiation {
            get {
                return ResourceManager.GetString("UnderwaterDayRadiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwater Day Storm Radiation.
        /// </summary>
        public static string UnderwaterDayStormRadiation {
            get {
                return ResourceManager.GetString("UnderwaterDayStormRadiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwater Day Storm Temp (celsius).
        /// </summary>
        public static string UnderwaterDayStormTemp {
            get {
                return ResourceManager.GetString("UnderwaterDayStormTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwater Day Storm Toxic.
        /// </summary>
        public static string UnderwaterDayStormToxic {
            get {
                return ResourceManager.GetString("UnderwaterDayStormToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwater Day Temp (celsius).
        /// </summary>
        public static string UnderwaterDayTemp {
            get {
                return ResourceManager.GetString("UnderwaterDayTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwater Day Toxic.
        /// </summary>
        public static string UnderwaterDayToxic {
            get {
                return ResourceManager.GetString("UnderwaterDayToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwater Night Storm Temp (celsius).
        /// </summary>
        public static string UnderwaterNightStormTemp {
            get {
                return ResourceManager.GetString("UnderwaterNightStormTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwater Night Temp (celsius).
        /// </summary>
        public static string UnderwaterNightTemp {
            get {
                return ResourceManager.GetString("UnderwaterNightTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Link.
        /// </summary>
        public static string WikiLink {
            get {
                return ResourceManager.GetString("WikiLink", resourceCulture);
            }
        }
    }
}
