using AGT.GalacticArchives.Core.Models.GameData;
using AutoMapper;

namespace AGT.GalacticArchives.Services.Mapping.TypeConverters;

public class GameDataTypeConverter :
    ITypeConverter<Dictionary<string, object>, Galaxy>,
    ITypeConverter<Dictionary<string, object>, Region>,
    ITypeConverter<Dictionary<string, object>, StarSystem>,
    ITypeConverter<Dictionary<string, object>, Planet>
{
    public Galaxy Convert(Dictionary<string, object> source, Galaxy destination, ResolutionContext context)
    {
        // TODO Replace this with Reflection
        return new Galaxy
        {
            GalaxyId = (Guid)source[nameof(Galaxy.GalaxyId)],
            Sequence = (int)source[nameof(Galaxy.Sequence)],
            Name = (string)source[nameof(Galaxy.Name)],
        };
    }

    public Region Convert(Dictionary<string, object> source, Region destination, ResolutionContext context)
    {
        // TODO Replace this with Reflection
        return new Region
        {
            RegionId = (Guid)source[nameof(Region.RegionId)],
            GalaxyId = (Guid)source[nameof(Region.GalaxyId)],
            Quadrant = (string?)source[nameof(Region.Quadrant)],
            AutoLatestSurvey = (string?)source[nameof(Region.AutoLatestSurvey)],
            DocSequence = (int)source[nameof(Region.DocSequence)],
            RegionAge = (float?)source[nameof(Region.CivilizedSpaceNotes)],
            Name = (string)source[nameof(Region.Name)],
            CivilizedBy = (string?)source[nameof(Region.CivilizedBy)],
            Coordinates = (string?)source[nameof(Region.Coordinates)],
            GameRelease = (string?)source[nameof(Region.GameRelease)],
            EarliestKnownSurveyorId = (string?)source[nameof(Region.EarliestKnownSurveyorId)],
            LatestKnownSurveyorId = (string?)source[nameof(Region.LatestKnownSurveyorId)],
            SummaryNotes = (string?)source[nameof(Region.SummaryNotes)],
            LocationNotes = (string?)source[nameof(Region.LocationNotes)],
            AdditionalNotes = (string?)source[nameof(Region.AdditionalNotes)],
            CivilizedSpaceNotes = (string?)source[nameof(Region.CivilizedSpaceNotes)],
            LowestKnownPhantomSystem = (string?)source[nameof(Region.LowestKnownPhantomSystem)],
            WikiLink = (string?)source[nameof(Region.WikiLink)],
            ExternalLink1 = (string?)source[nameof(Region.ExternalLink1)],
            VideoLink1 = (string?)source[nameof(Region.VideoLink1)],
            LightYearsFromCenter = (int?)source[nameof(Region.LightYearsFromCenter)],
            EarliestSystemDiscovery = (string?)source[nameof(Region.EarliestSystemDiscovery)],
            BaseCoord = (string?)source[nameof(Region.BaseCoord)],
            EarliestSurveyorWikiUser = (string?)source[nameof(Region.EarliestSurveyorWikiUser)],
            LatestSurveyorWikiUser = (string?)source[nameof(Region.LatestSurveyorWikiUser)],
            AdminNotes = (string?)source[nameof(Region.AdminNotes)],
            LegacyName = (string?)source[nameof(Region.LegacyName)],
            LegacyWikilink = (string?)source[nameof(Region.LegacyWikilink)],
            XXdec = (string?)source[nameof(Region.XXdec)],
            YYdec = (string?)source[nameof(Region.YYdec)],
            ZZdec = (string?)source[nameof(Region.ZZdec)],
            Glylphs = (string?)source[nameof(Region.Glylphs)],
            Version = (string?)source[nameof(Region.Version)],
        };
    }

    public StarSystem Convert(Dictionary<string, object> source, StarSystem destination, ResolutionContext context)
    {
        // TODO Replace this with Reflection
        return new StarSystem
        {
            StarSystemId = (Guid)source[nameof(StarSystem.StarSystemId)],
            Name = (string)source[nameof(StarSystem.Name)],
            AdminNotes = (string?)source[nameof(StarSystem.AdminNotes)],
            PlanetOfInterestId = (string?)source[nameof(StarSystem.PlanetOfInterestId)],
            DataQualityCheck = (string?)source[nameof(StarSystem.DataQualityCheck)],
            OriginalSystemName = (string?)source[nameof(StarSystem.OriginalSystemName)],
            GalacticCoordinates = (string)source[nameof(StarSystem.GalacticCoordinates)],
            GlyphCode = (string)source[nameof(StarSystem.GlyphCode)],
            RegionId = (Guid)source[nameof(StarSystem.RegionId)],
            SurveyorName = (string?)source[nameof(StarSystem.SurveyorName)],
            DiscoveredBy = (string?)source[nameof(StarSystem.DiscoveredBy)],
            SpecialInterest = (string?)source[nameof(StarSystem.SpecialInterest)],
            CivilizedBy = (string?)source[nameof(StarSystem.CivilizedBy)],
            StarCategory = (string?)source[nameof(StarSystem.StarCategory)],
            Color = (string?)source[nameof(StarSystem.Color)],
            GameRelease = (string?)source[nameof(StarSystem.GameRelease)],
            StarCount = (int?)source[nameof(StarSystem.StarCount)],
            NumberOfPlanets = (int?)source[nameof(StarSystem.NumberOfPlanets)],
            NumberOfMoons = (int?)source[nameof(StarSystem.NumberOfMoons)],
            LightYearsFromCenter = (int?)source[nameof(StarSystem.LightYearsFromCenter)],
            Buy = (float?)source[nameof(StarSystem.Buy)],
            Sell = (float?)source[nameof(StarSystem.Sell)],
            PlatformType = (string?)source[nameof(StarSystem.PlatformType)],
            GameModeType = (string?)source[nameof(StarSystem.GameModeType)],
            Faction = (string?)source[nameof(StarSystem.Faction)],
            EconomyType = (string?)source[nameof(StarSystem.EconomyType)],
            WealthType = (string?)source[nameof(StarSystem.WealthType)],
            ConflictType = (string?)source[nameof(StarSystem.ConflictType)],
            IsGiantSystem = (bool)source[nameof(StarSystem.IsGiantSystem)],
            IsDissonant = (bool)source[nameof(StarSystem.IsDissonant)],
            HasWater = (bool)source[nameof(StarSystem.HasWater)],
            DiscoveryDate = (string?)source[nameof(StarSystem.DiscoveryDate)],
            SurveyDate = (string?)source[nameof(StarSystem.SurveyDate)],
            SystemNameAllPlatforms = (string?)source[nameof(StarSystem.SystemNameAllPlatforms)],
            DiscoveredLinkOnWiki = (string?)source[nameof(StarSystem.DiscoveredLinkOnWiki)],
            Bases = (string?)source[nameof(StarSystem.Bases)],
            LightYearsFromCenterAutoEstimate = (int?)source[nameof(StarSystem.LightYearsFromCenterAutoEstimate)],
            KeySystemIndicator = (string?)source[nameof(StarSystem.KeySystemIndicator)],
            SpaceStationTradeItems = (HashSet<string?>)source[nameof(StarSystem.SpaceStationTradeItems)],
            ExoSuitSClassUpgradeModules = (HashSet<string?>)source[nameof(StarSystem.ExoSuitSClassUpgradeModules)],
            SpaceShipSClassUpgradeModules = (HashSet<string?>)source[nameof(StarSystem.SpaceShipSClassUpgradeModules)],
            MultiToolSClassUpgradeModules = (HashSet<string?>)source[nameof(StarSystem.MultiToolSClassUpgradeModules)],
            XCoordDec = (int?)source[nameof(StarSystem.XCoordDec)],
            YCoordDec = (int?)source[nameof(StarSystem.YCoordDec)],
            ZCoordDec = (int?)source[nameof(StarSystem.ZCoordDec)],
            Hex2DecSystemId = (int?)source[nameof(StarSystem.Hex2DecSystemId)],
            SummaryAdditions = (string?)source[nameof(StarSystem.SummaryAdditions)],
            DiscoveredNotes = (string?)source[nameof(StarSystem.DiscoveredNotes)],
            PlanetsTextNotes = (string?)source[nameof(StarSystem.PlanetsTextNotes)],
            StarshipsTextNotes = (string?)source[nameof(StarSystem.StarshipsTextNotes)],
            MTTextNotes = (string?)source[nameof(StarSystem.MTTextNotes)],
            LocInfoNotes = (string?)source[nameof(StarSystem.LocInfoNotes)],
            SpaceStationNotes = (string?)source[nameof(StarSystem.SpaceStationNotes)],
            AdditionalNotes = (string?)source[nameof(StarSystem.AdditionalNotes)],
            GalleryTextNotes = (string?)source[nameof(StarSystem.GalleryTextNotes)],
            IsPhantomSystem = (bool?)source[nameof(StarSystem.IsPhantomSystem)],
            HasCenterAccess = (bool?)source[nameof(StarSystem.HasCenterAccess)],
            BlackHoleDestination = (string?)source[nameof(StarSystem.BlackHoleDestination)],
            NMSWikiLink = (string?)source[nameof(StarSystem.NMSWikiLink)],
            ExternalLink1 = (string?)source[nameof(StarSystem.ExternalLink1)],
            ExternalLink2 = (string?)source[nameof(StarSystem.ExternalLink2)],
            ExternalLink3 = (string?)source[nameof(StarSystem.ExternalLink3)],
            VideoLink = (string?)source[nameof(StarSystem.VideoLink)],
            LegacyPCSystemName = (string?)source[nameof(StarSystem.LegacyPCSystemName)],
            LegacyPSSystemName = (string?)source[nameof(StarSystem.LegacyPSSystemName)],
            LegacyXboxSystemName = (string?)source[nameof(StarSystem.LegacyXboxSystemName)],
            LegacyPCDiscoverersGamerTagName = (string?)source[nameof(StarSystem.LegacyPCDiscoverersGamerTagName)],
            LegacyPSDiscoverersGamerTagName = (string?)source[nameof(StarSystem.LegacyPSDiscoverersGamerTagName)],
            LegacyXboxDiscoverersGamerTagName = (string?)source[nameof(StarSystem.LegacyXboxDiscoverersGamerTagName)],
            Evolution = (string?)source[nameof(StarSystem.Evolution)],
            SystemMisc = (string?)source[nameof(StarSystem.SystemMisc)],
        };
    }

    public Planet Convert(Dictionary<string, object> source, Planet destination, ResolutionContext context)
    {
        // TODO Replace this with Reflection
        return new Planet
        {
            PlanetId = (Guid)source[nameof(Planet.PlanetId)],
            Name = (string)source[nameof(Planet.Name)],
            PlanetNameAllPlatforms = (string?)source[nameof(Planet.PlanetNameAllPlatforms)],
            AdminNotes = (string?)source[nameof(Planet.AdminNotes)],
            DataQualityCheck = (string?)source[nameof(Planet.DataQualityCheck)],
            OriginalPlanetName = (string?)source[nameof(Planet.OriginalPlanetName)],
            PlanetMoonMatch = (string?)source[nameof(Planet.PlanetMoonMatch)],
            PlanetOrMoon = (string?)source[nameof(Planet.PlanetOrMoon)],
            RingsOrGiant = (string?)source[nameof(Planet.RingsOrGiant)],
            PlanetIdInSystem = (int?)source[nameof(Planet.PlanetIdInSystem)],
            BiomeType = (string?)source[nameof(Planet.BiomeType)],
            BiomeDescription = (string?)source[nameof(Planet.BiomeDescription)],
            IsInfected = (bool?)source[nameof(Planet.IsInfected)],
            Terrain = (string?)source[nameof(Planet.Terrain)],
            TypeOfLand = (string?)source[nameof(Planet.TypeOfLand)],
            ArchetypeOfLand = (string?)source[nameof(Planet.ArchetypeOfLand)],
            Weather = (string?)source[nameof(Planet.Weather)],
            ExtremeWeatherExcludingMegaExotic = (string?)source[nameof(Planet.ExtremeWeatherExcludingMegaExotic)],
            ExtremeWeatherInludingMegaExotic = (string?)source[nameof(Planet.ExtremeWeatherInludingMegaExotic)],
            PrimaryResource1 = (string?)source[nameof(Planet.PrimaryResource1)],
            PrimaryResource2 = (string?)source[nameof(Planet.PrimaryResource2)],
            PrimaryResource3 = (string?)source[nameof(Planet.PrimaryResource3)],
            BiomeResource = (string?)source[nameof(Planet.BiomeResource)],
            AtmosphereResource = (string?)source[nameof(Planet.AtmosphereResource)],
            AtmosphereDaytimeColor = (string?)source[nameof(Planet.AtmosphereDaytimeColor)],
            SpecialA = (string?)source[nameof(Planet.SpecialA)],
            ExtrasA = (string?)source[nameof(Planet.ExtrasA)],
            ExtrasB = (string?)source[nameof(Planet.ExtrasB)],
            ExtrasC = (string?)source[nameof(Planet.ExtrasC)],
            Glitches = (string?)source[nameof(Planet.Glitches)],
            AssignedRawIngredient = (string?)source[nameof(Planet.AssignedRawIngredient)],
            RawIngredients = (HashSet<string?>)source[nameof(Planet.RawIngredients)],
            Sentinel = (string?)source[nameof(Planet.Sentinel)],
            Flora = (string?)source[nameof(Planet.Flora)],
            Fauna = (string?)source[nameof(Planet.Fauna)],
            NumberOfFauna = (int?)source[nameof(Planet.NumberOfFauna)],
            Mode = (string?)source[nameof(Planet.Mode)],
            CivilizedBy = (string?)source[nameof(Planet.CivilizedBy)],
            DiscovererGamertag = (string?)source[nameof(Planet.DiscovererGamertag)],
            DiscoveredLinkOnWiki = (string?)source[nameof(Planet.DiscoveredLinkOnWiki)],
            DiscoveryDate = (string?)source[nameof(Planet.DiscoveryDate)],
            SurveyorGamertag = (string?)source[nameof(Planet.SurveyorGamertag)],
            SurveyDate = (string?)source[nameof(Planet.SurveyDate)],
            DiscoveryPlatform = (string?)source[nameof(Planet.DiscoveryPlatform)],
            SurveyReleaseEra = (string?)source[nameof(Planet.SurveyReleaseEra)],
            SummaryInfo = (string?)source[nameof(Planet.SummaryInfo)],
            AdditionalNotes = (string?)source[nameof(Planet.AdditionalNotes)],
            DayTemp = (string?)source[nameof(Planet.DayTemp)],
            DayRadiation = (string?)source[nameof(Planet.DayRadiation)],
            DayToxic = (string?)source[nameof(Planet.DayToxic)],
            NightTemp = (string?)source[nameof(Planet.NightTemp)],
            DayStormTemp = (string?)source[nameof(Planet.DayStormTemp)],
            DayStormRadiation = (string?)source[nameof(Planet.DayStormRadiation)],
            DayStormToxic = (string?)source[nameof(Planet.DayStormToxic)],
            NightStormTemp = (string?)source[nameof(Planet.NightStormTemp)],
            UndergroundDayTemp = (string?)source[nameof(Planet.UndergroundDayTemp)],
            UndergroundDayRadiation = (string?)source[nameof(Planet.UndergroundDayRadiation)],
            UndergroundDayToxic = (string?)source[nameof(Planet.UndergroundDayToxic)],
            UndergroundNightTemp = (string?)source[nameof(Planet.UndergroundNightTemp)],
            UnderwaterDayTemp = (string?)source[nameof(Planet.UnderwaterDayTemp)],
            UnderwaterDayRadiation = (string?)source[nameof(Planet.UnderwaterDayRadiation)],
            UnderwaterDayToxic = (string?)source[nameof(Planet.UnderwaterDayToxic)],
            UnderwaterNightTemp = (string?)source[nameof(Planet.UnderwaterNightTemp)],
            UnderwaterDayStormTemp = (string?)source[nameof(Planet.UnderwaterDayStormTemp)],
            UnderwaterDayStormRadiation = (string?)source[nameof(Planet.UnderwaterDayStormRadiation)],
            UnderwaterDayStormToxic = (string?)source[nameof(Planet.UnderwaterDayStormToxic)],
            UnderwaterNightStormTemp = (string?)source[nameof(Planet.UnderwaterNightStormTemp)],
            UndergroundDayStormTemp = (string?)source[nameof(Planet.UndergroundDayStormTemp)],
            UndergroundDayStormRadiation = (string?)source[nameof(Planet.UndergroundDayStormRadiation)],
            UndergroundDayStormToxic = (string?)source[nameof(Planet.UndergroundDayStormToxic)],
            UndergroundNightStormTemp = (string?)source[nameof(Planet.UndergroundNightStormTemp)],
            AgeOfPlanetInBillionsOfYears = (string?)source[nameof(Planet.AgeOfPlanetInBillionsOfYears)],
            AtmosphereGas1 = (string?)source[nameof(Planet.AtmosphereGas1)],
            AtmosphereGasPercentage1 = (string?)source[nameof(Planet.AtmosphereGasPercentage1)],
            AtmosphereGas2 = (string?)source[nameof(Planet.AtmosphereGas2)],
            AtmosphereGasPercentage2 = (string?)source[nameof(Planet.AtmosphereGasPercentage2)],
            PrimaryCoreElement = (string?)source[nameof(Planet.PrimaryCoreElement)],
            Geology = (string?)source[nameof(Planet.Geology)],
            OtherNotes = (string?)source[nameof(Planet.OtherNotes)],
            HasSandworms = (bool?)source[nameof(Planet.HasSandworms)],
            WikiLink = (string?)source[nameof(Planet.WikiLink)],
            PortalRepository = (string?)source[nameof(Planet.PortalRepository)],
            ExternalLink1 = (string?)source[nameof(Planet.ExternalLink1)],
            ExternalLink2 = (string?)source[nameof(Planet.ExternalLink2)],
            Garden = (string?)source[nameof(Planet.Garden)],
            DocumentSequence = (int?)source[nameof(Planet.DocumentSequence)],
            PlanetGlyphs = (string?)source[nameof(Planet.DocumentSequence)],
            ResearchTeam = (string?)source[nameof(Planet.ResearchTeam)],
            PlanetOrMoonAddedInOrigins = (string?)source[nameof(Planet.PlanetOrMoonAddedInOrigins)],
            LegacyPCPlanetName = (string?)source[nameof(Planet.LegacyPCPlanetName)],
            LegacyPCDiscoveryEra = (string?)source[nameof(Planet.LegacyPCDiscoveryEra)],
            LegacyPCDiscoverersGamerTagName = (string?)source[nameof(Planet.LegacyPCDiscoverersGamerTagName)],
            LegacyPCDiscoveryDate = (string?)source[nameof(Planet.LegacyPCDiscoveryDate)],
            LegacyPSPlanetName = (string?)source[nameof(Planet.LegacyPSPlanetName)],
            LegacyPSDiscoveryEra = (string?)source[nameof(Planet.LegacyPSDiscoveryEra)],
            LegacyPSDiscoverersGamerTagName = (string?)source[nameof(Planet.LegacyPSDiscoverersGamerTagName)],
            LegacyPSDiscoveryDate = (string?)source[nameof(Planet.LegacyPSDiscoveryDate)],
            LegacyXboxPlanetName = (string?)source[nameof(Planet.LegacyXboxPlanetName)],
            LegacyXboxDiscoveryEra = (string?)source[nameof(Planet.LegacyXboxDiscoveryEra)],
            LegacyXboxDiscoverersGamerTagName = (string?)source[nameof(Planet.LegacyXboxDiscoverersGamerTagName)],
            LegacyXboxDiscoveryDate = (string?)source[nameof(Planet.LegacyXboxDiscoveryDate)],
            HistoricalPlanetNameReset = (string?)source[nameof(Planet.HistoricalPlanetNameReset)],
            HistoricalPlanetNamePlatform = (string?)source[nameof(Planet.HistoricalPlanetNamePlatform)],
            HistoricalPlanetNameLastKnownEra = (string?)source[nameof(Planet.HistoricalPlanetNameLastKnownEra)],
            HistoricalPlanetDiscoverCreditBeforeReset = (string?)source[nameof(Planet.HistoricalPlanetDiscoverCreditBeforeReset)],
            LegacyWikiLinkPC = (string?)source[nameof(Planet.LegacyWikiLinkPC)],
            LegacyWikiLinkPS = (string?)source[nameof(Planet.LegacyWikiLinkPS)],
            LegacyWikiLinkXbox = (string?)source[nameof(Planet.LegacyWikiLinkXbox)],
            LegacyWikiLinkOther = (string?)source[nameof(Planet.LegacyWikiLinkOther)],
            GameVersionNumberForPage = (string?)source[nameof(Planet.GameVersionNumberForPage)],
            DocSeqCheck = (int?)source[nameof(Planet.DocSeqCheck)],
        };
    }
}