namespace AGT.GalacticArchives.Core.Models.Enums.Planet;

public enum FaunaGenusTypes
{
    Agnelis = 1,
    Anastomus,
    Anomalous,
    Arthropodae,
    Bos,
    Bosaquatica,
    Bosoptera,
    Chrysaora,
    Conokinis,
    Crustacea,
    Cycromys,
    Felidae,
    Felihex,
    Floradae,
    Hexungulatis,
    Hippocampus,
    Ictaloris,
    Krakenidae,
    Lok,
    Mechanoceris,
    Mobula,
    Mogara,
    Osteofelidae,
    Oxyacta,
    Prionace,
    Prionacefda,
    Prionterrae,
    Procavaquatica,
    Procavya,
    Protocaeli,
    Protosphaeridae,
    Prototerrae,
    Rangifae,
    Reococcyx,
    Rhopalocera,
    Shaihuluda,
    Spiralis,
    Talpidae,
    Tetraceris,
    Theroma,
    Tyranocae,
    Ungulatis,
}