//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EconomyTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EconomyTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.EconomyTypeResource", typeof(EconomyTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Materials.
        /// </summary>
        public static string AdvancedMaterials {
            get {
                return ResourceManager.GetString("AdvancedMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Unavailable.
        /// </summary>
        public static string DataUnavailable {
            get {
                return ResourceManager.GetString("DataUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Supply.
        /// </summary>
        public static string EnergySupply {
            get {
                return ResourceManager.GetString("EnergySupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Generation.
        /// </summary>
        public static string FuelGeneration {
            get {
                return ResourceManager.GetString("FuelGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Electric.
        /// </summary>
        public static string HighElectric {
            get {
                return ResourceManager.GetString("HighElectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Tech.
        /// </summary>
        public static string HighTech {
            get {
                return ResourceManager.GetString("HighTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Voltage.
        /// </summary>
        public static string HighVoltage {
            get {
                return ResourceManager.GetString("HighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Production.
        /// </summary>
        public static string MassProduction {
            get {
                return ResourceManager.GetString("MassProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Fusion.
        /// </summary>
        public static string MaterialFusion {
            get {
                return ResourceManager.GetString("MaterialFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal Processing.
        /// </summary>
        public static string MetalProcessing {
            get {
                return ResourceManager.GetString("MetalProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral Extraction.
        /// </summary>
        public static string MineralExtraction {
            get {
                return ResourceManager.GetString("MineralExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nano-construction.
        /// </summary>
        public static string NanoConstruction {
            get {
                return ResourceManager.GetString("NanoConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore Extraction.
        /// </summary>
        public static string OreExtraction {
            get {
                return ResourceManager.GetString("OreExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore Processing.
        /// </summary>
        public static string OreProcessing {
            get {
                return ResourceManager.GetString("OreProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Generation.
        /// </summary>
        public static string PowerGeneration {
            get {
                return ResourceManager.GetString("PowerGeneration", resourceCulture);
            }
        }
    }
}
