//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlayerBaseElementTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerBaseElementTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.PlayerItems.PlayerBaseElementTypeResource", typeof(PlayerBaseElementTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural Terminal.
        /// </summary>
        public static string AgriculturalTerminal {
            get {
                return ResourceManager.GetString("AgriculturalTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antimatter Reactor.
        /// </summary>
        public static string AntimatterReactor {
            get {
                return ResourceManager.GetString("AntimatterReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance Modifier.
        /// </summary>
        public static string AppearanceModifier {
            get {
                return ResourceManager.GetString("AppearanceModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere Harvester.
        /// </summary>
        public static string AtmosphereHarvester {
            get {
                return ResourceManager.GetString("AtmosphereHarvester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Feeder.
        /// </summary>
        public static string AutomatedFeeder {
            get {
                return ResourceManager.GetString("AutomatedFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Trap.
        /// </summary>
        public static string AutomatedTrap {
            get {
                return ResourceManager.GetString("AutomatedTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomous Mining Unit.
        /// </summary>
        public static string AutonomousMiningUnit {
            get {
                return ResourceManager.GetString("AutonomousMiningUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrel Fabricator.
        /// </summary>
        public static string BarrelFabricator {
            get {
                return ResourceManager.GetString("BarrelFabricator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Salvage Capsule.
        /// </summary>
        public static string BaseSalvageCapsule {
            get {
                return ResourceManager.GetString("BaseSalvageCapsule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Teleport Module.
        /// </summary>
        public static string BaseTeleportModule {
            get {
                return ResourceManager.GetString("BaseTeleportModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio-Dome.
        /// </summary>
        public static string BioDome {
            get {
                return ResourceManager.GetString("BioDome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biofuel Reactor.
        /// </summary>
        public static string BiofuelReactor {
            get {
                return ResourceManager.GetString("BiofuelReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytebeat Device.
        /// </summary>
        public static string BytebeatDevice {
            get {
                return ResourceManager.GetString("BytebeatDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colossus Geobay.
        /// </summary>
        public static string ColossusGeobay {
            get {
                return ResourceManager.GetString("ColossusGeobay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Research Unit.
        /// </summary>
        public static string ConstructionResearchUnit {
            get {
                return ResourceManager.GetString("ConstructionResearchUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Terminal.
        /// </summary>
        public static string ConstructionTerminal {
            get {
                return ResourceManager.GetString("ConstructionTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Fabricator.
        /// </summary>
        public static string CrateFabricator {
            get {
                return ResourceManager.GetString("CrateFabricator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deepwater Chamber.
        /// </summary>
        public static string DeepwaterChamber {
            get {
                return ResourceManager.GetString("DeepwaterChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Cloaking Unit.
        /// </summary>
        public static string ElectricalCloakingUnit {
            get {
                return ResourceManager.GetString("ElectricalCloakingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electromagnetic Generator.
        /// </summary>
        public static string ElectromagneticGenerator {
            get {
                return ResourceManager.GetString("ElectromagneticGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Heater.
        /// </summary>
        public static string EmergencyHeater {
            get {
                return ResourceManager.GetString("EmergencyHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exocraft Summoning Station.
        /// </summary>
        public static string ExocraftSummoningStation {
            get {
                return ResourceManager.GetString("ExocraftSummoningStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exocraft Terminal.
        /// </summary>
        public static string ExocraftTerminal {
            get {
                return ResourceManager.GetString("ExocraftTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fossil Display.
        /// </summary>
        public static string FossilDisplay {
            get {
                return ResourceManager.GetString("FossilDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galactic Trade Terminal.
        /// </summary>
        public static string GalacticTradeTerminal {
            get {
                return ResourceManager.GetString("GalacticTradeTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Protection Unit (Base Building).
        /// </summary>
        public static string HazardProtectionUnitBaseBuilding {
            get {
                return ResourceManager.GetString("HazardProtectionUnitBaseBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Station.
        /// </summary>
        public static string HealthStation {
            get {
                return ResourceManager.GetString("HealthStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holographic Chart Projector.
        /// </summary>
        public static string HolographicChartProjector {
            get {
                return ResourceManager.GetString("HolographicChartProjector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holographic Globe Gadget.
        /// </summary>
        public static string HolographicGlobeGadget {
            get {
                return ResourceManager.GetString("HolographicGlobeGadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydroponic Tray.
        /// </summary>
        public static string HydroponicTray {
            get {
                return ResourceManager.GetString("HydroponicTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing Pad.
        /// </summary>
        public static string LandingPad {
            get {
                return ResourceManager.GetString("LandingPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Refiner.
        /// </summary>
        public static string LargeRefiner {
            get {
                return ResourceManager.GetString("LargeRefiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livestock Unit.
        /// </summary>
        public static string LivestockUnit {
            get {
                return ResourceManager.GetString("LivestockUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Shelter.
        /// </summary>
        public static string MarineShelter {
            get {
                return ResourceManager.GetString("MarineShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Refiner.
        /// </summary>
        public static string MediumRefiner {
            get {
                return ResourceManager.GetString("MediumRefiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Module.
        /// </summary>
        public static string MessageModule {
            get {
                return ResourceManager.GetString("MessageModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minotaur Geobay.
        /// </summary>
        public static string MinotaurGeobay {
            get {
                return ResourceManager.GetString("MinotaurGeobay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon Pool Floor.
        /// </summary>
        public static string MoonPoolFloor {
            get {
                return ResourceManager.GetString("MoonPoolFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautilon Chamber.
        /// </summary>
        public static string NautilonChamber {
            get {
                return ResourceManager.GetString("NautilonChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Box.
        /// </summary>
        public static string NoiseBox {
            get {
                return ResourceManager.GetString("NoiseBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomad Geobay.
        /// </summary>
        public static string NomadGeobay {
            get {
                return ResourceManager.GetString("NomadGeobay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrient Processor.
        /// </summary>
        public static string NutrientProcessor {
            get {
                return ResourceManager.GetString("NutrientProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen Harvester.
        /// </summary>
        public static string OxygenHarvester {
            get {
                return ResourceManager.GetString("OxygenHarvester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilgrim Geobay.
        /// </summary>
        public static string PilgrimGeobay {
            get {
                return ResourceManager.GetString("PilgrimGeobay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planetary Globe.
        /// </summary>
        public static string PlanetaryGlobe {
            get {
                return ResourceManager.GetString("PlanetaryGlobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Reality Generator.
        /// </summary>
        public static string PocketRealityGenerator {
            get {
                return ResourceManager.GetString("PocketRealityGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Refiner.
        /// </summary>
        public static string PortableRefiner {
            get {
                return ResourceManager.GetString("PortableRefiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Force Amplifier.
        /// </summary>
        public static string RaceForceAmplifier {
            get {
                return ResourceManager.GetString("RaceForceAmplifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Initiator.
        /// </summary>
        public static string RaceInitiator {
            get {
                return ResourceManager.GetString("RaceInitiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Obstacle.
        /// </summary>
        public static string RaceObstacle {
            get {
                return ResourceManager.GetString("RaceObstacle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roamer Geobay.
        /// </summary>
        public static string RoamerGeobay {
            get {
                return ResourceManager.GetString("RoamerGeobay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Point.
        /// </summary>
        public static string SavePoint {
            get {
                return ResourceManager.GetString("SavePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Terminal.
        /// </summary>
        public static string ScienceTerminal {
            get {
                return ResourceManager.GetString("ScienceTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Station.
        /// </summary>
        public static string ShieldStation {
            get {
                return ResourceManager.GetString("ShieldStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-Range Teleporter.
        /// </summary>
        public static string ShortRangeTeleporter {
            get {
                return ResourceManager.GetString("ShortRangeTeleporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Booster.
        /// </summary>
        public static string SignalBooster {
            get {
                return ResourceManager.GetString("SignalBooster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Aquarium.
        /// </summary>
        public static string SmallAquarium {
            get {
                return ResourceManager.GetString("SmallAquarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Panel.
        /// </summary>
        public static string SolarPanel {
            get {
                return ResourceManager.GetString("SolarPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere Creator.
        /// </summary>
        public static string SphereCreator {
            get {
                return ResourceManager.GetString("SphereCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Planter.
        /// </summary>
        public static string StandingPlanter {
            get {
                return ResourceManager.GetString("StandingPlanter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Container.
        /// </summary>
        public static string StorageContainer {
            get {
                return ResourceManager.GetString("StorageContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Depot.
        /// </summary>
        public static string SupplyDepot {
            get {
                return ResourceManager.GetString("SupplyDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons Terminal.
        /// </summary>
        public static string WeaponsTerminal {
            get {
                return ResourceManager.GetString("WeaponsTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonder Projector.
        /// </summary>
        public static string WonderProjector {
            get {
                return ResourceManager.GetString("WonderProjector", resourceCulture);
            }
        }
    }
}
