//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StarshipSubtypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StarshipSubtypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.StarshipSubtypeResource", typeof(StarshipSubtypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic Ball.
        /// </summary>
        public static string ExoticBall {
            get {
                return ResourceManager.GetString("ExoticBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic Guppy.
        /// </summary>
        public static string ExoticGuppy {
            get {
                return ResourceManager.GetString("ExoticGuppy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic Mosquito.
        /// </summary>
        public static string ExoticMosquito {
            get {
                return ResourceManager.GetString("ExoticMosquito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic Royal.
        /// </summary>
        public static string ExoticRoyal {
            get {
                return ResourceManager.GetString("ExoticRoyal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic Squid.
        /// </summary>
        public static string ExoticSquid {
            get {
                return ResourceManager.GetString("ExoticSquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Dragonfly.
        /// </summary>
        public static string ExplorerDragonfly {
            get {
                return ResourceManager.GetString("ExplorerDragonfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Dragonfly-D.
        /// </summary>
        public static string ExplorerDragonflyD {
            get {
                return ResourceManager.GetString("ExplorerDragonflyD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Dragonfly-F.
        /// </summary>
        public static string ExplorerDragonflyF {
            get {
                return ResourceManager.GetString("ExplorerDragonflyF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Dragonfly-S.
        /// </summary>
        public static string ExplorerDragonflyS {
            get {
                return ResourceManager.GetString("ExplorerDragonflyS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Euclid.
        /// </summary>
        public static string ExplorerEuclid {
            get {
                return ResourceManager.GetString("ExplorerEuclid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Firefly.
        /// </summary>
        public static string ExplorerFirefly {
            get {
                return ResourceManager.GetString("ExplorerFirefly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Firefly-D.
        /// </summary>
        public static string ExplorerFireflyD {
            get {
                return ResourceManager.GetString("ExplorerFireflyD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Firefly-F.
        /// </summary>
        public static string ExplorerFireflyF {
            get {
                return ResourceManager.GetString("ExplorerFireflyF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Firefly-S.
        /// </summary>
        public static string ExplorerFireflyS {
            get {
                return ResourceManager.GetString("ExplorerFireflyS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Hesperius.
        /// </summary>
        public static string ExplorerHesperius {
            get {
                return ResourceManager.GetString("ExplorerHesperius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Alpha.
        /// </summary>
        public static string FighterAlpha {
            get {
                return ResourceManager.GetString("FighterAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Hotrod.
        /// </summary>
        public static string FighterHotrod {
            get {
                return ResourceManager.GetString("FighterHotrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Needle.
        /// </summary>
        public static string FighterNeedle {
            get {
                return ResourceManager.GetString("FighterNeedle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Omega.
        /// </summary>
        public static string FighterOmega {
            get {
                return ResourceManager.GetString("FighterOmega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Radiant.
        /// </summary>
        public static string FighterRadiant {
            get {
                return ResourceManager.GetString("FighterRadiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Sleek.
        /// </summary>
        public static string FighterSleek {
            get {
                return ResourceManager.GetString("FighterSleek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Speeder.
        /// </summary>
        public static string FighterSpeeder {
            get {
                return ResourceManager.GetString("FighterSpeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Turbine.
        /// </summary>
        public static string FighterTurbine {
            get {
                return ResourceManager.GetString("FighterTurbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Vector.
        /// </summary>
        public static string FighterVector {
            get {
                return ResourceManager.GetString("FighterVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Battleship.
        /// </summary>
        public static string FreighterBattleship {
            get {
                return ResourceManager.GetString("FreighterBattleship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Blade.
        /// </summary>
        public static string FreighterBlade {
            get {
                return ResourceManager.GetString("FreighterBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Cargo.
        /// </summary>
        public static string FreighterCargo {
            get {
                return ResourceManager.GetString("FreighterCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Centrifuge.
        /// </summary>
        public static string FreighterCentrifuge {
            get {
                return ResourceManager.GetString("FreighterCentrifuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Derelict.
        /// </summary>
        public static string FreighterDerelict {
            get {
                return ResourceManager.GetString("FreighterDerelict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Dreadnought.
        /// </summary>
        public static string FreighterDreadnought {
            get {
                return ResourceManager.GetString("FreighterDreadnought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Enterprise.
        /// </summary>
        public static string FreighterEnterprise {
            get {
                return ResourceManager.GetString("FreighterEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Galleon.
        /// </summary>
        public static string FreighterGalleon {
            get {
                return ResourceManager.GetString("FreighterGalleon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Hammerhead.
        /// </summary>
        public static string FreighterHammerhead {
            get {
                return ResourceManager.GetString("FreighterHammerhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Imperial.
        /// </summary>
        public static string FreighterImperial {
            get {
                return ResourceManager.GetString("FreighterImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Iris.
        /// </summary>
        public static string FreighterIris {
            get {
                return ResourceManager.GetString("FreighterIris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Oculus.
        /// </summary>
        public static string FreighterOculus {
            get {
                return ResourceManager.GetString("FreighterOculus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Regular.
        /// </summary>
        public static string FreighterRegular {
            get {
                return ResourceManager.GetString("FreighterRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Resurgent.
        /// </summary>
        public static string FreighterResurgent {
            get {
                return ResourceManager.GetString("FreighterResurgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Revolver.
        /// </summary>
        public static string FreighterRevolver {
            get {
                return ResourceManager.GetString("FreighterRevolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Sentinel.
        /// </summary>
        public static string FreighterSentinel {
            get {
                return ResourceManager.GetString("FreighterSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Venator.
        /// </summary>
        public static string FreighterVenator {
            get {
                return ResourceManager.GetString("FreighterVenator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Combat.
        /// </summary>
        public static string FrigateCombat {
            get {
                return ResourceManager.GetString("FrigateCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Ethereal.
        /// </summary>
        public static string FrigateEthereal {
            get {
                return ResourceManager.GetString("FrigateEthereal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Exploration.
        /// </summary>
        public static string FrigateExploration {
            get {
                return ResourceManager.GetString("FrigateExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Gimp.
        /// </summary>
        public static string FrigateGimp {
            get {
                return ResourceManager.GetString("FrigateGimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Industrial.
        /// </summary>
        public static string FrigateIndustrial {
            get {
                return ResourceManager.GetString("FrigateIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Leviathan.
        /// </summary>
        public static string FrigateLeviathan {
            get {
                return ResourceManager.GetString("FrigateLeviathan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Mono-Leviathan.
        /// </summary>
        public static string FrigateMonoLeviathan {
            get {
                return ResourceManager.GetString("FrigateMonoLeviathan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Runt.
        /// </summary>
        public static string FrigateRunt {
            get {
                return ResourceManager.GetString("FrigateRunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Support.
        /// </summary>
        public static string FrigateSupport {
            get {
                return ResourceManager.GetString("FrigateSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate Trade.
        /// </summary>
        public static string FrigateTrade {
            get {
                return ResourceManager.GetString("FrigateTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Aviator.
        /// </summary>
        public static string HaulerAviator {
            get {
                return ResourceManager.GetString("HaulerAviator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Bulker.
        /// </summary>
        public static string HaulerBulker {
            get {
                return ResourceManager.GetString("HaulerBulker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Hydraulic.
        /// </summary>
        public static string HaulerHydraulic {
            get {
                return ResourceManager.GetString("HaulerHydraulic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Iron Vulture.
        /// </summary>
        public static string HaulerIronVulture {
            get {
                return ResourceManager.GetString("HaulerIronVulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Longshore.
        /// </summary>
        public static string HaulerLongshore {
            get {
                return ResourceManager.GetString("HaulerLongshore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Negotiator.
        /// </summary>
        public static string HaulerNegotiator {
            get {
                return ResourceManager.GetString("HaulerNegotiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Strato-Haul.
        /// </summary>
        public static string HaulerStratoHaul {
            get {
                return ResourceManager.GetString("HaulerStratoHaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Supercruise.
        /// </summary>
        public static string HaulerSupercruise {
            get {
                return ResourceManager.GetString("HaulerSupercruise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Type-11.
        /// </summary>
        public static string HaulerType11 {
            get {
                return ResourceManager.GetString("HaulerType11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor I-Wing.
        /// </summary>
        public static string InterceptorIWing {
            get {
                return ResourceManager.GetString("InterceptorIWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor I-Wing Mandible.
        /// </summary>
        public static string InterceptorIWingMandible {
            get {
                return ResourceManager.GetString("InterceptorIWingMandible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor I-Wing Pincer.
        /// </summary>
        public static string InterceptorIWingPincer {
            get {
                return ResourceManager.GetString("InterceptorIWingPincer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor U-Wing.
        /// </summary>
        public static string InterceptorUWing {
            get {
                return ResourceManager.GetString("InterceptorUWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor U-Wing Mandible.
        /// </summary>
        public static string InterceptorUWingMandible {
            get {
                return ResourceManager.GetString("InterceptorUWingMandible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor U-Wing Pincer.
        /// </summary>
        public static string InterceptorUWingPincer {
            get {
                return ResourceManager.GetString("InterceptorUWingPincer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor X-Wing.
        /// </summary>
        public static string InterceptorXWing {
            get {
                return ResourceManager.GetString("InterceptorXWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor X-Wing Mandible.
        /// </summary>
        public static string InterceptorXWingMandible {
            get {
                return ResourceManager.GetString("InterceptorXWingMandible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor X-Wing Pincer.
        /// </summary>
        public static string InterceptorXWingPincer {
            get {
                return ResourceManager.GetString("InterceptorXWingPincer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Ship Anvil.
        /// </summary>
        public static string LivingShipAnvil {
            get {
                return ResourceManager.GetString("LivingShipAnvil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Ship Compact.
        /// </summary>
        public static string LivingShipCompact {
            get {
                return ResourceManager.GetString("LivingShipCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Ship Hammerhead.
        /// </summary>
        public static string LivingShipHammerhead {
            get {
                return ResourceManager.GetString("LivingShipHammerhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Ship Shark.
        /// </summary>
        public static string LivingShipShark {
            get {
                return ResourceManager.GetString("LivingShipShark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Ship Tusked.
        /// </summary>
        public static string LivingShipTusked {
            get {
                return ResourceManager.GetString("LivingShipTusked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Box.
        /// </summary>
        public static string ShuttleBox {
            get {
                return ResourceManager.GetString("ShuttleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Double Tube.
        /// </summary>
        public static string ShuttleDoubleTube {
            get {
                return ResourceManager.GetString("ShuttleDoubleTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Tube.
        /// </summary>
        public static string ShuttleTube {
            get {
                return ResourceManager.GetString("ShuttleTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Archanid.
        /// </summary>
        public static string SolarArchanid {
            get {
                return ResourceManager.GetString("SolarArchanid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Exocet.
        /// </summary>
        public static string SolarExocet {
            get {
                return ResourceManager.GetString("SolarExocet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Falcon.
        /// </summary>
        public static string SolarFalcon {
            get {
                return ResourceManager.GetString("SolarFalcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Raven.
        /// </summary>
        public static string SolarRaven {
            get {
                return ResourceManager.GetString("SolarRaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Starwolf.
        /// </summary>
        public static string SolarStarwolf {
            get {
                return ResourceManager.GetString("SolarStarwolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Turbofan.
        /// </summary>
        public static string SolarTurbofan {
            get {
                return ResourceManager.GetString("SolarTurbofan", resourceCulture);
            }
        }
    }
}
