//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StarshipThrusterTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StarshipThrusterTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.PlayerItems.StarshipThrusterTypeResource", typeof(StarshipThrusterTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Large Double Thruster.
        /// </summary>
        public static string ExplorerLargeDoubleThruster {
            get {
                return ResourceManager.GetString("ExplorerLargeDoubleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Quad Thruster.
        /// </summary>
        public static string ExplorerQuadThruster {
            get {
                return ResourceManager.GetString("ExplorerQuadThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Quintuple Thruster.
        /// </summary>
        public static string ExplorerQuintupleThruster {
            get {
                return ResourceManager.GetString("ExplorerQuintupleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Sextuple Thruster.
        /// </summary>
        public static string ExplorerSextupleThruster {
            get {
                return ResourceManager.GetString("ExplorerSextupleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Single Thruster.
        /// </summary>
        public static string ExplorerSingleThruster {
            get {
                return ResourceManager.GetString("ExplorerSingleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Small Double Thruster.
        /// </summary>
        public static string ExplorerSmallDoubleThruster {
            get {
                return ResourceManager.GetString("ExplorerSmallDoubleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Triple Thruster.
        /// </summary>
        public static string ExplorerTripleThruster {
            get {
                return ResourceManager.GetString("ExplorerTripleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Mono Thruster.
        /// </summary>
        public static string FighterMonoThruster {
            get {
                return ResourceManager.GetString("FighterMonoThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Tri-Booster.
        /// </summary>
        public static string FighterTriBooster {
            get {
                return ResourceManager.GetString("FighterTriBooster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Vector Thruster.
        /// </summary>
        public static string FighterVectorThruster {
            get {
                return ResourceManager.GetString("FighterVectorThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Airlift Thruster.
        /// </summary>
        public static string HaulerAirliftThruster {
            get {
                return ResourceManager.GetString("HaulerAirliftThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Duo-Max Engine.
        /// </summary>
        public static string HaulerDuoMaxEngine {
            get {
                return ResourceManager.GetString("HaulerDuoMaxEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler F-Wing Airlift Thruster.
        /// </summary>
        public static string HaulerFWingAirliftThruster {
            get {
                return ResourceManager.GetString("HaulerFWingAirliftThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler F-Wing Megalith Engine.
        /// </summary>
        public static string HaulerFWingMegalithEngine {
            get {
                return ResourceManager.GetString("HaulerFWingMegalithEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Iron Vulture Engine.
        /// </summary>
        public static string HaulerIronVultureEngine {
            get {
                return ResourceManager.GetString("HaulerIronVultureEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler Megalith Engine.
        /// </summary>
        public static string HaulerMegalithEngine {
            get {
                return ResourceManager.GetString("HaulerMegalithEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler S-Wing Airlift Thruster.
        /// </summary>
        public static string HaulerSWingAirliftThruster {
            get {
                return ResourceManager.GetString("HaulerSWingAirliftThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler S-Wing Megalith Engine.
        /// </summary>
        public static string HaulerSWingMegalithEngine {
            get {
                return ResourceManager.GetString("HaulerSWingMegalithEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor Pointed.
        /// </summary>
        public static string InterceptorPointed {
            get {
                return ResourceManager.GetString("InterceptorPointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor Vented.
        /// </summary>
        public static string InterceptorVented {
            get {
                return ResourceManager.GetString("InterceptorVented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor Wedged.
        /// </summary>
        public static string InterceptorWedged {
            get {
                return ResourceManager.GetString("InterceptorWedged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Ship Dual Thruster.
        /// </summary>
        public static string LivingShipDualThruster {
            get {
                return ResourceManager.GetString("LivingShipDualThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Ship Single Thruster.
        /// </summary>
        public static string LivingShipSingleThruster {
            get {
                return ResourceManager.GetString("LivingShipSingleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Ship Triple Thruster.
        /// </summary>
        public static string LivingShipTripleThruster {
            get {
                return ResourceManager.GetString("LivingShipTripleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Large Double Thruster.
        /// </summary>
        public static string ShuttleLargeDoubleThruster {
            get {
                return ResourceManager.GetString("ShuttleLargeDoubleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Quad Thruster.
        /// </summary>
        public static string ShuttleQuadThruster {
            get {
                return ResourceManager.GetString("ShuttleQuadThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Quintuple Thruster.
        /// </summary>
        public static string ShuttleQuintupleThruster {
            get {
                return ResourceManager.GetString("ShuttleQuintupleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Sextuple Thruster.
        /// </summary>
        public static string ShuttleSextupleThruster {
            get {
                return ResourceManager.GetString("ShuttleSextupleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Single Thruster.
        /// </summary>
        public static string ShuttleSingleThruster {
            get {
                return ResourceManager.GetString("ShuttleSingleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Small Double Thruster.
        /// </summary>
        public static string ShuttleSmallDoubleThruster {
            get {
                return ResourceManager.GetString("ShuttleSmallDoubleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle Triple Thruster.
        /// </summary>
        public static string ShuttleTripleThruster {
            get {
                return ResourceManager.GetString("ShuttleTripleThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Crescent Solar Sail.
        /// </summary>
        public static string SolarCrescentSolarSail {
            get {
                return ResourceManager.GetString("SolarCrescentSolarSail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Hex Solar Sail.
        /// </summary>
        public static string SolarHexSolarSail {
            get {
                return ResourceManager.GetString("SolarHexSolarSail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Square-Rig Solar Sail.
        /// </summary>
        public static string SolarSquareRigSolarSail {
            get {
                return ResourceManager.GetString("SolarSquareRigSolarSail", resourceCulture);
            }
        }
    }
}
