//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGT.GalacticArchives.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StarshipLocationTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StarshipLocationTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGT.GalacticArchives.Globalization.StarshipLocationTypeResource", typeof(StarshipLocationTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colossal Archive.
        /// </summary>
        public static string ColossalArchive {
            get {
                return ResourceManager.GetString("ColossalArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crashed Ship.
        /// </summary>
        public static string CrashedShip {
            get {
                return ResourceManager.GetString("CrashedShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freighter Bay.
        /// </summary>
        public static string FreighterBay {
            get {
                return ResourceManager.GetString("FreighterBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitable Base.
        /// </summary>
        public static string HabitableBase {
            get {
                return ResourceManager.GetString("HabitableBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Settlement.
        /// </summary>
        public static string MinorSettlement {
            get {
                return ResourceManager.GetString("MinorSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Anomaly.
        /// </summary>
        public static string SpaceAnomaly {
            get {
                return ResourceManager.GetString("SpaceAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Battle.
        /// </summary>
        public static string SpaceBattle {
            get {
                return ResourceManager.GetString("SpaceBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Station.
        /// </summary>
        public static string SpaceStation {
            get {
                return ResourceManager.GetString("SpaceStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Post.
        /// </summary>
        public static string TradingPost {
            get {
                return ResourceManager.GetString("TradingPost", resourceCulture);
            }
        }
    }
}
